/* 
 * Store Information
 *
 * Get Store Information endpoint, manage store profile settings.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using StoreInfo.Client;
using StoreInfo.Api;
using StoreInfo.Model;

namespace StoreInfo.Test
{
    /// <summary>
    ///  Class for testing StoreInformationApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class StoreInformationApiTests
    {
        private StoreInformationApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new StoreInformationApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of StoreInformationApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' StoreInformationApi
            //Assert.IsInstanceOfType(typeof(StoreInformationApi), instance, "instance is a StoreInformationApi");
        }

        /// <summary>
        /// Test StoreGet
        /// </summary>
        [Test]
        public void StoreGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accept = null;
            //string contentType = null;
            //var response = instance.StoreGet(accept, contentType);
            //Assert.IsInstanceOf<StoreInformation> (response, "response is StoreInformation");
        }
    }

}
