/* 
 * Store Information
 *
 * Get Store Information endpoint, manage store profile settings.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using StoreInfo.Api;
using StoreInfo.Model;
using StoreInfo.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace StoreInfo.Test
{
    /// <summary>
    ///  Class for testing DateFormat
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DateFormatTests
    {
        // TODO uncomment below to declare an instance variable for DateFormat
        //private DateFormat instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DateFormat
            //instance = new DateFormat();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DateFormat
        /// </summary>
        [Test]
        public void DateFormatInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DateFormat
            //Assert.IsInstanceOfType<DateFormat> (instance, "variable 'instance' is a DateFormat");
        }


        /// <summary>
        /// Test the property 'Display'
        /// </summary>
        [Test]
        public void DisplayTest()
        {
            // TODO unit test for the property 'Display'
        }
        /// <summary>
        /// Test the property 'Export'
        /// </summary>
        [Test]
        public void ExportTest()
        {
            // TODO unit test for the property 'Export'
        }
        /// <summary>
        /// Test the property 'ExtendedDisplay'
        /// </summary>
        [Test]
        public void ExtendedDisplayTest()
        {
            // TODO unit test for the property 'ExtendedDisplay'
        }

    }

}
