/* 
 * Store Information
 *
 * Get Store Information endpoint, manage store profile settings.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using StoreInfo.Api;
using StoreInfo.Model;
using StoreInfo.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace StoreInfo.Test
{
    /// <summary>
    ///  Class for testing TimeStampFull1
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TimeStampFull1Tests
    {
        // TODO uncomment below to declare an instance variable for TimeStampFull1
        //private TimeStampFull1 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TimeStampFull1
            //instance = new TimeStampFull1();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TimeStampFull1
        /// </summary>
        [Test]
        public void TimeStampFull1InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TimeStampFull1
            //Assert.IsInstanceOfType<TimeStampFull1> (instance, "variable 'instance' is a TimeStampFull1");
        }


        /// <summary>
        /// Test the property 'Time'
        /// </summary>
        [Test]
        public void TimeTest()
        {
            // TODO unit test for the property 'Time'
        }

    }

}
