/* 
 * Themes
 *
 * Backup, restore, download, and activate themes; and, get the status of theme jobs and read theme configurations.  - [OAuth Scopes](#oauth-scopes) - [Authentication](#authentication)  For more information on OAuth Scopes, see: [Authentication](https://developer.bigcommerce.com/api-docs/getting-started/authentication).  ## Authentication  Requests can be authenticated by sending an `access_token` via `X-Auth-Token` HTTP header:  ```http GET /stores/{$$.env.store_hash}/v3/catalog/summary host: api.bigcommerce.com Accept: application/json X-Auth-Token: {access_token} ```  ### OAuth Scopes | UI Name                                      | Permission | Parameter                                     | |- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -|- -- -- -- -- -- -|- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --| | Themes                                       | modify     | `store_themes_manage`                         |
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Themes.Api;
using Themes.Model;
using Themes.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Themes.Test
{
    /// <summary>
    ///  Class for testing Pagination1Links
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class Pagination1LinksTests
    {
        // TODO uncomment below to declare an instance variable for Pagination1Links
        //private Pagination1Links instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Pagination1Links
            //instance = new Pagination1Links();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Pagination1Links
        /// </summary>
        [Test]
        public void Pagination1LinksInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Pagination1Links
            //Assert.IsInstanceOfType<Pagination1Links> (instance, "variable 'instance' is a Pagination1Links");
        }


        /// <summary>
        /// Test the property 'Previous'
        /// </summary>
        [Test]
        public void PreviousTest()
        {
            // TODO unit test for the property 'Previous'
        }
        /// <summary>
        /// Test the property 'Current'
        /// </summary>
        [Test]
        public void CurrentTest()
        {
            // TODO unit test for the property 'Current'
        }
        /// <summary>
        /// Test the property 'Next'
        /// </summary>
        [Test]
        public void NextTest()
        {
            // TODO unit test for the property 'Next'
        }

    }

}
