/* 
 * Themes
 *
 * Backup, restore, download, and activate themes; and, get the status of theme jobs and read theme configurations.  - [OAuth Scopes](#oauth-scopes) - [Authentication](#authentication)  For more information on OAuth Scopes, see: [Authentication](https://developer.bigcommerce.com/api-docs/getting-started/authentication).  ## Authentication  Requests can be authenticated by sending an `access_token` via `X-Auth-Token` HTTP header:  ```http GET /stores/{$$.env.store_hash}/v3/catalog/summary host: api.bigcommerce.com Accept: application/json X-Auth-Token: {access_token} ```  ### OAuth Scopes | UI Name                                      | Permission | Parameter                                     | |- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -|- -- -- -- -- -- -|- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --| | Themes                                       | modify     | `store_themes_manage`                         |
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = BigCommerce.Client.SwaggerDateConverter;

namespace BigCommerce.Model
{
    /// <summary>
    /// These are the minium request headers needed for BigCommerce. 
    /// </summary>
    [DataContract]
        public partial class RequestHeaders :  IEquatable<RequestHeaders>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RequestHeaders" /> class.
        /// </summary>
        /// <param name="xAuthClient">xAuthClient.</param>
        /// <param name="accepts">accepts (default to &quot;application/json&quot;).</param>
        public RequestHeaders(string xAuthClient = default(string), string accepts = "application/json")
        {
            this.XAuthClient = xAuthClient;
            // use default value if no "accepts" provided
            if (accepts == null)
            {
                this.Accepts = "application/json";
            }
            else
            {
                this.Accepts = accepts;
            }
        }
        
        /// <summary>
        /// Gets or Sets XAuthClient
        /// </summary>
        [DataMember(Name="X-Auth-Client", EmitDefaultValue=false)]
        public string XAuthClient { get; set; }

        /// <summary>
        /// Gets or Sets Accepts
        /// </summary>
        [DataMember(Name="Accepts", EmitDefaultValue=false)]
        public string Accepts { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class RequestHeaders {\n");
            sb.Append("  XAuthClient: ").Append(XAuthClient).Append("\n");
            sb.Append("  Accepts: ").Append(Accepts).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as RequestHeaders);
        }

        /// <summary>
        /// Returns true if RequestHeaders instances are equal
        /// </summary>
        /// <param name="input">Instance of RequestHeaders to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RequestHeaders input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.XAuthClient == input.XAuthClient ||
                    (this.XAuthClient != null &&
                    this.XAuthClient.Equals(input.XAuthClient))
                ) && 
                (
                    this.Accepts == input.Accepts ||
                    (this.Accepts != null &&
                    this.Accepts.Equals(input.Accepts))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.XAuthClient != null)
                    hashCode = hashCode * 59 + this.XAuthClient.GetHashCode();
                if (this.Accepts != null)
                    hashCode = hashCode * 59 + this.Accepts.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
