/* 
 * Widgets
 *
 * Create and manage [widgets](/api-docs/storefront/widgets/widgets-overview), widget templates, regions, and placements.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Widgets.Client;
using Widgets.Api;
using Widgets.Model;

namespace Widgets.Test
{
    /// <summary>
    ///  Class for testing WidgetTemplateApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class WidgetTemplateApiTests
    {
        private WidgetTemplateApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new WidgetTemplateApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WidgetTemplateApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' WidgetTemplateApi
            //Assert.IsInstanceOfType(typeof(WidgetTemplateApi), instance, "instance is a WidgetTemplateApi");
        }

        /// <summary>
        /// Test CreateWidgetTemplate
        /// </summary>
        [Test]
        public void CreateWidgetTemplateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //WidgetTemplatePost1 body = null;
            //string accept = null;
            //string contentType = null;
            //var response = instance.CreateWidgetTemplate(body, accept, contentType);
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
        /// <summary>
        /// Test DeleteWidgetTemplate
        /// </summary>
        [Test]
        public void DeleteWidgetTemplateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid? uuid = null;
            //string accept = null;
            //string contentType = null;
            //instance.DeleteWidgetTemplate(uuid, accept, contentType);
            
        }
        /// <summary>
        /// Test GetWidgetTemplate
        /// </summary>
        [Test]
        public void GetWidgetTemplateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid? uuid = null;
            //string accept = null;
            //string contentType = null;
            //var response = instance.GetWidgetTemplate(uuid, accept, contentType);
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
        /// <summary>
        /// Test GetWidgetTemplates
        /// </summary>
        [Test]
        public void GetWidgetTemplatesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? page = null;
            //int? limit = null;
            //string widgetTemplateKind = null;
            //string accept = null;
            //string contentType = null;
            //var response = instance.GetWidgetTemplates(page, limit, widgetTemplateKind, accept, contentType);
            //Assert.IsInstanceOf<InlineResponse200> (response, "response is InlineResponse200");
        }
        /// <summary>
        /// Test UpdateWidgetTemplate
        /// </summary>
        [Test]
        public void UpdateWidgetTemplateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //WidgetTemplatePut1 body = null;
            //Guid? uuid = null;
            //string accept = null;
            //string contentType = null;
            //var response = instance.UpdateWidgetTemplate(body, uuid, accept, contentType);
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
    }

}
