/* 
 * Carts
 *
 * Create a cart using BigCommerce cart logic.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BigCommerce.Api;
using BigCommerce.Model;
using BigCommerce.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BigCommerce.Test
{
    /// <summary>
    ///  Class for testing CartLineItemUpdatePost2
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CartLineItemUpdatePost2Tests
    {
        // TODO uncomment below to declare an instance variable for CartLineItemUpdatePost2
        //private CartLineItemUpdatePost2 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CartLineItemUpdatePost2
            //instance = new CartLineItemUpdatePost2();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CartLineItemUpdatePost2
        /// </summary>
        [Test]
        public void CartLineItemUpdatePost2InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CartLineItemUpdatePost2
            //Assert.IsInstanceOfType<CartLineItemUpdatePost2> (instance, "variable 'instance' is a CartLineItemUpdatePost2");
        }


        /// <summary>
        /// Test the property 'LineItems'
        /// </summary>
        [Test]
        public void LineItemsTest()
        {
            // TODO unit test for the property 'LineItems'
        }
        /// <summary>
        /// Test the property 'GiftCertificates'
        /// </summary>
        [Test]
        public void GiftCertificatesTest()
        {
            // TODO unit test for the property 'GiftCertificates'
        }
        /// <summary>
        /// Test the property 'CustomItems'
        /// </summary>
        [Test]
        public void CustomItemsTest()
        {
            // TODO unit test for the property 'CustomItems'
        }

    }

}
