/* 
 * Themes
 *
 * Backup, restore, download, and activate themes; and, get the status of theme jobs and read theme configurations.  - [OAuth Scopes](#oauth-scopes) - [Authentication](#authentication)  For more information on OAuth Scopes, see: [Authentication](https://developer.bigcommerce.com/api-docs/getting-started/authentication).  ## Authentication  Requests can be authenticated by sending an `access_token` via `X-Auth-Token` HTTP header:  ```http GET /stores/{$$.env.store_hash}/v3/catalog/summary host: api.bigcommerce.com Accept: application/json X-Auth-Token: {access_token} ```  ### OAuth Scopes | UI Name                                      | Permission | Parameter                                     | |- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -|- -- -- -- -- -- -|- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --| | Themes                                       | modify     | `store_themes_manage`                         |
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Themes.Client.SwaggerDateConverter;

namespace Themes.Model
{
    /// <summary>
    /// A theme.
    /// </summary>
    [DataContract]
        public partial class ThemeConfigurationFull :  IEquatable<ThemeConfigurationFull>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ThemeConfigurationFull" /> class.
        /// </summary>
        /// <param name="uuid">uuid.</param>
        /// <param name="themeUuid">The Theme to which the Configuration belongs..</param>
        /// <param name="variationId">The Variation to which the Configuration belongs..</param>
        /// <param name="settings">The content of the configuration, which is a JSON object which will vary in structure from theme to theme..</param>
        /// <param name="dateCreated">dateCreated.</param>
        /// <param name="siteId">Site ID to which this configuration belongs. Will be 0 for the original configuration for a Theme..</param>
        public ThemeConfigurationFull(string uuid = default(string), string themeUuid = default(string), string variationId = default(string), Object settings = default(Object), string dateCreated = default(string), int? siteId = default(int?))
        {
            this.Uuid = uuid;
            this.ThemeUuid = themeUuid;
            this.VariationId = variationId;
            this.Settings = settings;
            this.DateCreated = dateCreated;
            this.SiteId = siteId;
        }
        
        /// <summary>
        /// Gets or Sets Uuid
        /// </summary>
        [DataMember(Name="uuid", EmitDefaultValue=false)]
        public string Uuid { get; set; }

        /// <summary>
        /// The Theme to which the Configuration belongs.
        /// </summary>
        /// <value>The Theme to which the Configuration belongs.</value>
        [DataMember(Name="theme_uuid", EmitDefaultValue=false)]
        public string ThemeUuid { get; set; }

        /// <summary>
        /// The Variation to which the Configuration belongs.
        /// </summary>
        /// <value>The Variation to which the Configuration belongs.</value>
        [DataMember(Name="variation_id", EmitDefaultValue=false)]
        public string VariationId { get; set; }

        /// <summary>
        /// The content of the configuration, which is a JSON object which will vary in structure from theme to theme.
        /// </summary>
        /// <value>The content of the configuration, which is a JSON object which will vary in structure from theme to theme.</value>
        [DataMember(Name="settings", EmitDefaultValue=false)]
        public Object Settings { get; set; }

        /// <summary>
        /// Gets or Sets DateCreated
        /// </summary>
        [DataMember(Name="date_created", EmitDefaultValue=false)]
        public string DateCreated { get; set; }

        /// <summary>
        /// Site ID to which this configuration belongs. Will be 0 for the original configuration for a Theme.
        /// </summary>
        /// <value>Site ID to which this configuration belongs. Will be 0 for the original configuration for a Theme.</value>
        [DataMember(Name="site_id", EmitDefaultValue=false)]
        public int? SiteId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ThemeConfigurationFull {\n");
            sb.Append("  Uuid: ").Append(Uuid).Append("\n");
            sb.Append("  ThemeUuid: ").Append(ThemeUuid).Append("\n");
            sb.Append("  VariationId: ").Append(VariationId).Append("\n");
            sb.Append("  Settings: ").Append(Settings).Append("\n");
            sb.Append("  DateCreated: ").Append(DateCreated).Append("\n");
            sb.Append("  SiteId: ").Append(SiteId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ThemeConfigurationFull);
        }

        /// <summary>
        /// Returns true if ThemeConfigurationFull instances are equal
        /// </summary>
        /// <param name="input">Instance of ThemeConfigurationFull to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ThemeConfigurationFull input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Uuid == input.Uuid ||
                    (this.Uuid != null &&
                    this.Uuid.Equals(input.Uuid))
                ) && 
                (
                    this.ThemeUuid == input.ThemeUuid ||
                    (this.ThemeUuid != null &&
                    this.ThemeUuid.Equals(input.ThemeUuid))
                ) && 
                (
                    this.VariationId == input.VariationId ||
                    (this.VariationId != null &&
                    this.VariationId.Equals(input.VariationId))
                ) && 
                (
                    this.Settings == input.Settings ||
                    (this.Settings != null &&
                    this.Settings.Equals(input.Settings))
                ) && 
                (
                    this.DateCreated == input.DateCreated ||
                    (this.DateCreated != null &&
                    this.DateCreated.Equals(input.DateCreated))
                ) && 
                (
                    this.SiteId == input.SiteId ||
                    (this.SiteId != null &&
                    this.SiteId.Equals(input.SiteId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Uuid != null)
                    hashCode = hashCode * 59 + this.Uuid.GetHashCode();
                if (this.ThemeUuid != null)
                    hashCode = hashCode * 59 + this.ThemeUuid.GetHashCode();
                if (this.VariationId != null)
                    hashCode = hashCode * 59 + this.VariationId.GetHashCode();
                if (this.Settings != null)
                    hashCode = hashCode * 59 + this.Settings.GetHashCode();
                if (this.DateCreated != null)
                    hashCode = hashCode * 59 + this.DateCreated.GetHashCode();
                if (this.SiteId != null)
                    hashCode = hashCode * 59 + this.SiteId.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
