/* 
 * Subscribers
 *
 * Manage subscribers.  ### OAuth Scopes |  **UI Name** | **Permission** | **Parameter** | | - -- | - -- | - -- | |  Customers | modify | `store_v2_customers` | |  Customers | read-only | `store_v2_customers_read_only` |  ### Headers  |Header|Parameter|Description| |-|-|-| |`X-Auth-Client`|`client_id`|Obtained by creating an API account or installing an app in a BigCommerce control panel.| |`X-Auth-Token`|`access_token `|Obtained by creating an API account or installing an app in a BigCommerce control panel.|  ### Example  ```http GET /stores/{$$.env.store_hash}/v3/catalog/summary host: api.bigcommerce.com Content-Type: application/json X-Auth-Client: {client_id} X-Auth-Token: {access_token} ```  * For more information on Authenticating BigCommerce APIs, see: [Authentication](https://developer.bigcommerce.com/api-docs/getting-started/authentication). 
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BigCommerce.Api;
using BigCommerce.Model;
using BigCommerce.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BigCommerce.Test
{
    /// <summary>
    ///  Class for testing AllOfSubscriberResponseData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AllOfSubscriberResponseDataTests
    {
        // TODO uncomment below to declare an instance variable for AllOfSubscriberResponseData
        //private AllOfSubscriberResponseData instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AllOfSubscriberResponseData
            //instance = new AllOfSubscriberResponseData();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AllOfSubscriberResponseData
        /// </summary>
        [Test]
        public void AllOfSubscriberResponseDataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AllOfSubscriberResponseData
            //Assert.IsInstanceOfType<AllOfSubscriberResponseData> (instance, "variable 'instance' is a AllOfSubscriberResponseData");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'DateModified'
        /// </summary>
        [Test]
        public void DateModifiedTest()
        {
            // TODO unit test for the property 'DateModified'
        }
        /// <summary>
        /// Test the property 'DateCreated'
        /// </summary>
        [Test]
        public void DateCreatedTest()
        {
            // TODO unit test for the property 'DateCreated'
        }

    }

}
