/* 
 * Carts
 *
 * Create a cart using BigCommerce cart logic.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Carts.Api;
using Carts.Model;
using Carts.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Carts.Test
{
    /// <summary>
    ///  Class for testing CartUpdatePutRequestData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CartUpdatePutRequestDataTests
    {
        // TODO uncomment below to declare an instance variable for CartUpdatePutRequestData
        //private CartUpdatePutRequestData instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CartUpdatePutRequestData
            //instance = new CartUpdatePutRequestData();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CartUpdatePutRequestData
        /// </summary>
        [Test]
        public void CartUpdatePutRequestDataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CartUpdatePutRequestData
            //Assert.IsInstanceOfType<CartUpdatePutRequestData> (instance, "variable 'instance' is a CartUpdatePutRequestData");
        }


        /// <summary>
        /// Test the property 'CustomerId'
        /// </summary>
        [Test]
        public void CustomerIdTest()
        {
            // TODO unit test for the property 'CustomerId'
        }

    }

}
