/* 
 * Carts
 *
 * Create a cart using BigCommerce cart logic.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Carts.Api;
using Carts.Model;
using Carts.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Carts.Test
{
    /// <summary>
    ///  Class for testing ContactEntity
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ContactEntityTests
    {
        // TODO uncomment below to declare an instance variable for ContactEntity
        //private ContactEntity instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ContactEntity
            //instance = new ContactEntity();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ContactEntity
        /// </summary>
        [Test]
        public void ContactEntityInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ContactEntity
            //Assert.IsInstanceOfType<ContactEntity> (instance, "variable 'instance' is a ContactEntity");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Test]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }

    }

}
