/* 
 * Carts
 *
 * Create a cart using BigCommerce cart logic.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Carts.Api;
using Carts.Model;
using Carts.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Carts.Test
{
    /// <summary>
    ///  Class for testing Currency1
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class Currency1Tests
    {
        // TODO uncomment below to declare an instance variable for Currency1
        //private Currency1 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Currency1
            //instance = new Currency1();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Currency1
        /// </summary>
        [Test]
        public void Currency1InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Currency1
            //Assert.IsInstanceOfType<Currency1> (instance, "variable 'instance' is a Currency1");
        }


        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Test]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }

    }

}
