/* 
 * Carts
 *
 * Create a cart using BigCommerce cart logic.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Carts.Api;
using Carts.Model;
using Carts.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Carts.Test
{
    /// <summary>
    ///  Class for testing ItemCustom
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ItemCustomTests
    {
        // TODO uncomment below to declare an instance variable for ItemCustom
        //private ItemCustom instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ItemCustom
            //instance = new ItemCustom();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ItemCustom
        /// </summary>
        [Test]
        public void ItemCustomInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ItemCustom
            //Assert.IsInstanceOfType<ItemCustom> (instance, "variable 'instance' is a ItemCustom");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Sku'
        /// </summary>
        [Test]
        public void SkuTest()
        {
            // TODO unit test for the property 'Sku'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Quantity'
        /// </summary>
        [Test]
        public void QuantityTest()
        {
            // TODO unit test for the property 'Quantity'
        }
        /// <summary>
        /// Test the property 'ListPrice'
        /// </summary>
        [Test]
        public void ListPriceTest()
        {
            // TODO unit test for the property 'ListPrice'
        }
        /// <summary>
        /// Test the property 'ExtendedListPrice'
        /// </summary>
        [Test]
        public void ExtendedListPriceTest()
        {
            // TODO unit test for the property 'ExtendedListPrice'
        }

    }

}
