/* 
 * Widgets
 *
 * Create and manage [widgets](/api-docs/storefront/widgets/widgets-overview), widget templates, regions, and placements.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Widgets.Client.SwaggerDateConverter;

namespace Widgets.Model
{
    /// <summary>
    /// NewmodelInner
    /// </summary>
    [DataContract]
        public partial class NewmodelInner :  IEquatable<NewmodelInner>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="NewmodelInner" /> class.
        /// </summary>
        /// <param name="type">type.</param>
        /// <param name="label">label.</param>
        /// <param name="id">id.</param>
        /// <param name="_default">_default.</param>
        /// <param name="typeMeta">typeMeta.</param>
        /// <param name="conditional">conditional.</param>
        public NewmodelInner(string type = default(string), string label = default(string), string id = default(string), int? _default = default(int?), string typeMeta = default(string), string conditional = default(string))
        {
            this.Type = type;
            this.Label = label;
            this.Id = id;
            this.Default = _default;
            this.TypeMeta = typeMeta;
            this.Conditional = conditional;
        }
        
        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name="type", EmitDefaultValue=false)]
        public string Type { get; set; }

        /// <summary>
        /// Gets or Sets Label
        /// </summary>
        [DataMember(Name="label", EmitDefaultValue=false)]
        public string Label { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets Default
        /// </summary>
        [DataMember(Name="default", EmitDefaultValue=false)]
        public int? Default { get; set; }

        /// <summary>
        /// Gets or Sets TypeMeta
        /// </summary>
        [DataMember(Name="typeMeta", EmitDefaultValue=false)]
        public string TypeMeta { get; set; }

        /// <summary>
        /// Gets or Sets Conditional
        /// </summary>
        [DataMember(Name="conditional", EmitDefaultValue=false)]
        public string Conditional { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class NewmodelInner {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Label: ").Append(Label).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Default: ").Append(Default).Append("\n");
            sb.Append("  TypeMeta: ").Append(TypeMeta).Append("\n");
            sb.Append("  Conditional: ").Append(Conditional).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as NewmodelInner);
        }

        /// <summary>
        /// Returns true if NewmodelInner instances are equal
        /// </summary>
        /// <param name="input">Instance of NewmodelInner to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(NewmodelInner input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Type == input.Type ||
                    (this.Type != null &&
                    this.Type.Equals(input.Type))
                ) && 
                (
                    this.Label == input.Label ||
                    (this.Label != null &&
                    this.Label.Equals(input.Label))
                ) && 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.Default == input.Default ||
                    (this.Default != null &&
                    this.Default.Equals(input.Default))
                ) && 
                (
                    this.TypeMeta == input.TypeMeta ||
                    (this.TypeMeta != null &&
                    this.TypeMeta.Equals(input.TypeMeta))
                ) && 
                (
                    this.Conditional == input.Conditional ||
                    (this.Conditional != null &&
                    this.Conditional.Equals(input.Conditional))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Type != null)
                    hashCode = hashCode * 59 + this.Type.GetHashCode();
                if (this.Label != null)
                    hashCode = hashCode * 59 + this.Label.GetHashCode();
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.Default != null)
                    hashCode = hashCode * 59 + this.Default.GetHashCode();
                if (this.TypeMeta != null)
                    hashCode = hashCode * 59 + this.TypeMeta.GetHashCode();
                if (this.Conditional != null)
                    hashCode = hashCode * 59 + this.Conditional.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
