/* 
 * Widgets
 *
 * Create and manage [widgets](/api-docs/storefront/widgets/widgets-overview), widget templates, regions, and placements.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Widgets.Client.SwaggerDateConverter;

namespace Widgets.Model
{
    /// <summary>
    /// Additional information needed based on the selected setting type.
    /// </summary>
    [DataContract]
        public partial class WidgetSchemaTabTypeMeta :  IEquatable<WidgetSchemaTabTypeMeta>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WidgetSchemaTabTypeMeta" /> class.
        /// </summary>
        /// <param name="selectOptions">selectOptions.</param>
        public WidgetSchemaTabTypeMeta(List<WidgetSchemaTabTypeMetaSelectOptions> selectOptions = default(List<WidgetSchemaTabTypeMetaSelectOptions>))
        {
            this.SelectOptions = selectOptions;
        }
        
        /// <summary>
        /// Gets or Sets SelectOptions
        /// </summary>
        [DataMember(Name="selectOptions", EmitDefaultValue=false)]
        public List<WidgetSchemaTabTypeMetaSelectOptions> SelectOptions { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class WidgetSchemaTabTypeMeta {\n");
            sb.Append("  SelectOptions: ").Append(SelectOptions).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as WidgetSchemaTabTypeMeta);
        }

        /// <summary>
        /// Returns true if WidgetSchemaTabTypeMeta instances are equal
        /// </summary>
        /// <param name="input">Instance of WidgetSchemaTabTypeMeta to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(WidgetSchemaTabTypeMeta input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.SelectOptions == input.SelectOptions ||
                    this.SelectOptions != null &&
                    input.SelectOptions != null &&
                    this.SelectOptions.SequenceEqual(input.SelectOptions)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.SelectOptions != null)
                    hashCode = hashCode * 59 + this.SelectOptions.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
