/* 
 * Widgets
 *
 * Create and manage [widgets](/api-docs/storefront/widgets/widgets-overview), widget templates, regions, and placements.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Widgets.Client.SwaggerDateConverter;

namespace Widgets.Model
{
    /// <summary>
    /// WidgetPost1
    /// </summary>
    [DataContract]
        public partial class WidgetPost1 :  IEquatable<WidgetPost1>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WidgetPost1" /> class.
        /// </summary>
        /// <param name="name">User friendly name. (required).</param>
        /// <param name="description">The user-friendly description..</param>
        /// <param name="widgetConfiguration">The JSON data that populates the template..</param>
        /// <param name="widgetTemplateUuid">The widget template UUID. (required).</param>
        public WidgetPost1(string name = default(string), string description = default(string), Object widgetConfiguration = default(Object), string widgetTemplateUuid = default(string))
        {
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new InvalidDataException("name is a required property for WidgetPost1 and cannot be null");
            }
            else
            {
                this.Name = name;
            }
            // to ensure "widgetTemplateUuid" is required (not null)
            if (widgetTemplateUuid == null)
            {
                throw new InvalidDataException("widgetTemplateUuid is a required property for WidgetPost1 and cannot be null");
            }
            else
            {
                this.WidgetTemplateUuid = widgetTemplateUuid;
            }
            this.Description = description;
            this.WidgetConfiguration = widgetConfiguration;
        }
        
        /// <summary>
        /// User friendly name.
        /// </summary>
        /// <value>User friendly name.</value>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// The user-friendly description.
        /// </summary>
        /// <value>The user-friendly description.</value>
        [DataMember(Name="description", EmitDefaultValue=false)]
        public string Description { get; set; }

        /// <summary>
        /// The JSON data that populates the template.
        /// </summary>
        /// <value>The JSON data that populates the template.</value>
        [DataMember(Name="widget_configuration", EmitDefaultValue=false)]
        public Object WidgetConfiguration { get; set; }

        /// <summary>
        /// The widget template UUID.
        /// </summary>
        /// <value>The widget template UUID.</value>
        [DataMember(Name="widget_template_uuid", EmitDefaultValue=false)]
        public string WidgetTemplateUuid { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class WidgetPost1 {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  WidgetConfiguration: ").Append(WidgetConfiguration).Append("\n");
            sb.Append("  WidgetTemplateUuid: ").Append(WidgetTemplateUuid).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as WidgetPost1);
        }

        /// <summary>
        /// Returns true if WidgetPost1 instances are equal
        /// </summary>
        /// <param name="input">Instance of WidgetPost1 to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(WidgetPost1 input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.Description == input.Description ||
                    (this.Description != null &&
                    this.Description.Equals(input.Description))
                ) && 
                (
                    this.WidgetConfiguration == input.WidgetConfiguration ||
                    (this.WidgetConfiguration != null &&
                    this.WidgetConfiguration.Equals(input.WidgetConfiguration))
                ) && 
                (
                    this.WidgetTemplateUuid == input.WidgetTemplateUuid ||
                    (this.WidgetTemplateUuid != null &&
                    this.WidgetTemplateUuid.Equals(input.WidgetTemplateUuid))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.Description != null)
                    hashCode = hashCode * 59 + this.Description.GetHashCode();
                if (this.WidgetConfiguration != null)
                    hashCode = hashCode * 59 + this.WidgetConfiguration.GetHashCode();
                if (this.WidgetTemplateUuid != null)
                    hashCode = hashCode * 59 + this.WidgetTemplateUuid.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
