/* 
 * Carts
 *
 * Create a cart using BigCommerce cart logic.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = BigCommerce.Client.SwaggerDateConverter;

namespace BigCommerce.Model
{
    /// <summary>
    /// CartRequestData
    /// </summary>
    [DataContract]
        public partial class CartRequestData :  IEquatable<CartRequestData>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CartRequestData" /> class.
        /// </summary>
        /// <param name="lineItems">lineItems.</param>
        /// <param name="giftCertificates">giftCertificates.</param>
        /// <param name="channelId">If no channel is specified, defaults to 1. .</param>
        public CartRequestData(List<LineItemRequestData> lineItems = default(List<LineItemRequestData>), List<LineItemGiftCertificateRequestData> giftCertificates = default(List<LineItemGiftCertificateRequestData>), int? channelId = default(int?))
        {
            this.LineItems = lineItems;
            this.GiftCertificates = giftCertificates;
            this.ChannelId = channelId;
        }
        
        /// <summary>
        /// Gets or Sets LineItems
        /// </summary>
        [DataMember(Name="line_items", EmitDefaultValue=false)]
        public List<LineItemRequestData> LineItems { get; set; }

        /// <summary>
        /// Gets or Sets GiftCertificates
        /// </summary>
        [DataMember(Name="gift_certificates", EmitDefaultValue=false)]
        public List<LineItemGiftCertificateRequestData> GiftCertificates { get; set; }

        /// <summary>
        /// If no channel is specified, defaults to 1. 
        /// </summary>
        /// <value>If no channel is specified, defaults to 1. </value>
        [DataMember(Name="channel_id", EmitDefaultValue=false)]
        public int? ChannelId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CartRequestData {\n");
            sb.Append("  LineItems: ").Append(LineItems).Append("\n");
            sb.Append("  GiftCertificates: ").Append(GiftCertificates).Append("\n");
            sb.Append("  ChannelId: ").Append(ChannelId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CartRequestData);
        }

        /// <summary>
        /// Returns true if CartRequestData instances are equal
        /// </summary>
        /// <param name="input">Instance of CartRequestData to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CartRequestData input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.LineItems == input.LineItems ||
                    this.LineItems != null &&
                    input.LineItems != null &&
                    this.LineItems.SequenceEqual(input.LineItems)
                ) && 
                (
                    this.GiftCertificates == input.GiftCertificates ||
                    this.GiftCertificates != null &&
                    input.GiftCertificates != null &&
                    this.GiftCertificates.SequenceEqual(input.GiftCertificates)
                ) && 
                (
                    this.ChannelId == input.ChannelId ||
                    (this.ChannelId != null &&
                    this.ChannelId.Equals(input.ChannelId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.LineItems != null)
                    hashCode = hashCode * 59 + this.LineItems.GetHashCode();
                if (this.GiftCertificates != null)
                    hashCode = hashCode * 59 + this.GiftCertificates.GetHashCode();
                if (this.ChannelId != null)
                    hashCode = hashCode * 59 + this.ChannelId.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
