/* 
 * Carts
 *
 * Create a cart using BigCommerce cart logic.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = BigCommerce.Client.SwaggerDateConverter;

namespace BigCommerce.Model
{
    /// <summary>
    /// A cart contains a collection of items, prices, discounts, etc.. It does not contain customer-related data.
    /// </summary>
    [DataContract]
        public partial class CartFull :  IEquatable<CartFull>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CartFull" /> class.
        /// </summary>
        /// <param name="id">Cart ID, provided after creating a cart with a POST..</param>
        /// <param name="parentId">Bundled items will have their parent&#x27;s item Id..</param>
        /// <param name="customerId">ID of the customer to which the cart belongs..</param>
        /// <param name="email">The cart&#x27;s email. This is the same email that is used in the billing address.</param>
        /// <param name="currency">currency.</param>
        /// <param name="taxIncluded">taxIncluded.</param>
        /// <param name="baseAmount">Cost of cart&#x27;s contents, before applying discounts..</param>
        /// <param name="discountAmount">Discounted amount..</param>
        /// <param name="cartAmount">Sum of line-items amounts, minus cart-level discounts and coupons. This amount includes taxes (where applicable)..</param>
        /// <param name="coupons">coupons.</param>
        /// <param name="discounts">discounts.</param>
        /// <param name="lineItems">lineItems.</param>
        /// <param name="createdTime">Time when the cart was created..</param>
        /// <param name="updatedTime">Time when the cart was last updated..</param>
        /// <param name="channelId">If no channel is specified, defaults to 1. .</param>
        public CartFull(string id = default(string), string parentId = default(string), int? customerId = default(int?), string email = default(string), Currency1 currency = default(Currency1), bool? taxIncluded = default(bool?), decimal? baseAmount = default(decimal?), decimal? discountAmount = default(decimal?), decimal? cartAmount = default(decimal?), List<AppliedCoupon> coupons = default(List<AppliedCoupon>), List<AppliedDiscount> discounts = default(List<AppliedDiscount>), List<LineItem> lineItems = default(List<LineItem>), string createdTime = default(string), string updatedTime = default(string), int? channelId = default(int?))
        {
            this.Id = id;
            this.ParentId = parentId;
            this.CustomerId = customerId;
            this.Email = email;
            this.Currency = currency;
            this.TaxIncluded = taxIncluded;
            this.BaseAmount = baseAmount;
            this.DiscountAmount = discountAmount;
            this.CartAmount = cartAmount;
            this.Coupons = coupons;
            this.Discounts = discounts;
            this.LineItems = lineItems;
            this.CreatedTime = createdTime;
            this.UpdatedTime = updatedTime;
            this.ChannelId = channelId;
        }
        
        /// <summary>
        /// Cart ID, provided after creating a cart with a POST.
        /// </summary>
        /// <value>Cart ID, provided after creating a cart with a POST.</value>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public string Id { get; set; }

        /// <summary>
        /// Bundled items will have their parent&#x27;s item Id.
        /// </summary>
        /// <value>Bundled items will have their parent&#x27;s item Id.</value>
        [DataMember(Name="parent_id", EmitDefaultValue=false)]
        public string ParentId { get; set; }

        /// <summary>
        /// ID of the customer to which the cart belongs.
        /// </summary>
        /// <value>ID of the customer to which the cart belongs.</value>
        [DataMember(Name="customer_id", EmitDefaultValue=false)]
        public int? CustomerId { get; set; }

        /// <summary>
        /// The cart&#x27;s email. This is the same email that is used in the billing address
        /// </summary>
        /// <value>The cart&#x27;s email. This is the same email that is used in the billing address</value>
        [DataMember(Name="email", EmitDefaultValue=false)]
        public string Email { get; set; }

        /// <summary>
        /// Gets or Sets Currency
        /// </summary>
        [DataMember(Name="currency", EmitDefaultValue=false)]
        public Currency1 Currency { get; set; }

        /// <summary>
        /// Gets or Sets TaxIncluded
        /// </summary>
        [DataMember(Name="tax_included", EmitDefaultValue=false)]
        public bool? TaxIncluded { get; set; }

        /// <summary>
        /// Cost of cart&#x27;s contents, before applying discounts.
        /// </summary>
        /// <value>Cost of cart&#x27;s contents, before applying discounts.</value>
        [DataMember(Name="base_amount", EmitDefaultValue=false)]
        public decimal? BaseAmount { get; set; }

        /// <summary>
        /// Discounted amount.
        /// </summary>
        /// <value>Discounted amount.</value>
        [DataMember(Name="discount_amount", EmitDefaultValue=false)]
        public decimal? DiscountAmount { get; set; }

        /// <summary>
        /// Sum of line-items amounts, minus cart-level discounts and coupons. This amount includes taxes (where applicable).
        /// </summary>
        /// <value>Sum of line-items amounts, minus cart-level discounts and coupons. This amount includes taxes (where applicable).</value>
        [DataMember(Name="cart_amount", EmitDefaultValue=false)]
        public decimal? CartAmount { get; set; }

        /// <summary>
        /// Gets or Sets Coupons
        /// </summary>
        [DataMember(Name="coupons", EmitDefaultValue=false)]
        public List<AppliedCoupon> Coupons { get; set; }

        /// <summary>
        /// Gets or Sets Discounts
        /// </summary>
        [DataMember(Name="discounts", EmitDefaultValue=false)]
        public List<AppliedDiscount> Discounts { get; set; }

        /// <summary>
        /// Gets or Sets LineItems
        /// </summary>
        [DataMember(Name="line_items", EmitDefaultValue=false)]
        public List<LineItem> LineItems { get; set; }

        /// <summary>
        /// Time when the cart was created.
        /// </summary>
        /// <value>Time when the cart was created.</value>
        [DataMember(Name="created_time", EmitDefaultValue=false)]
        public string CreatedTime { get; set; }

        /// <summary>
        /// Time when the cart was last updated.
        /// </summary>
        /// <value>Time when the cart was last updated.</value>
        [DataMember(Name="updated_time", EmitDefaultValue=false)]
        public string UpdatedTime { get; set; }

        /// <summary>
        /// If no channel is specified, defaults to 1. 
        /// </summary>
        /// <value>If no channel is specified, defaults to 1. </value>
        [DataMember(Name="channel_id", EmitDefaultValue=false)]
        public int? ChannelId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CartFull {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  ParentId: ").Append(ParentId).Append("\n");
            sb.Append("  CustomerId: ").Append(CustomerId).Append("\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  Currency: ").Append(Currency).Append("\n");
            sb.Append("  TaxIncluded: ").Append(TaxIncluded).Append("\n");
            sb.Append("  BaseAmount: ").Append(BaseAmount).Append("\n");
            sb.Append("  DiscountAmount: ").Append(DiscountAmount).Append("\n");
            sb.Append("  CartAmount: ").Append(CartAmount).Append("\n");
            sb.Append("  Coupons: ").Append(Coupons).Append("\n");
            sb.Append("  Discounts: ").Append(Discounts).Append("\n");
            sb.Append("  LineItems: ").Append(LineItems).Append("\n");
            sb.Append("  CreatedTime: ").Append(CreatedTime).Append("\n");
            sb.Append("  UpdatedTime: ").Append(UpdatedTime).Append("\n");
            sb.Append("  ChannelId: ").Append(ChannelId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CartFull);
        }

        /// <summary>
        /// Returns true if CartFull instances are equal
        /// </summary>
        /// <param name="input">Instance of CartFull to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CartFull input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.ParentId == input.ParentId ||
                    (this.ParentId != null &&
                    this.ParentId.Equals(input.ParentId))
                ) && 
                (
                    this.CustomerId == input.CustomerId ||
                    (this.CustomerId != null &&
                    this.CustomerId.Equals(input.CustomerId))
                ) && 
                (
                    this.Email == input.Email ||
                    (this.Email != null &&
                    this.Email.Equals(input.Email))
                ) && 
                (
                    this.Currency == input.Currency ||
                    (this.Currency != null &&
                    this.Currency.Equals(input.Currency))
                ) && 
                (
                    this.TaxIncluded == input.TaxIncluded ||
                    (this.TaxIncluded != null &&
                    this.TaxIncluded.Equals(input.TaxIncluded))
                ) && 
                (
                    this.BaseAmount == input.BaseAmount ||
                    (this.BaseAmount != null &&
                    this.BaseAmount.Equals(input.BaseAmount))
                ) && 
                (
                    this.DiscountAmount == input.DiscountAmount ||
                    (this.DiscountAmount != null &&
                    this.DiscountAmount.Equals(input.DiscountAmount))
                ) && 
                (
                    this.CartAmount == input.CartAmount ||
                    (this.CartAmount != null &&
                    this.CartAmount.Equals(input.CartAmount))
                ) && 
                (
                    this.Coupons == input.Coupons ||
                    this.Coupons != null &&
                    input.Coupons != null &&
                    this.Coupons.SequenceEqual(input.Coupons)
                ) && 
                (
                    this.Discounts == input.Discounts ||
                    this.Discounts != null &&
                    input.Discounts != null &&
                    this.Discounts.SequenceEqual(input.Discounts)
                ) && 
                (
                    this.LineItems == input.LineItems ||
                    this.LineItems != null &&
                    input.LineItems != null &&
                    this.LineItems.SequenceEqual(input.LineItems)
                ) && 
                (
                    this.CreatedTime == input.CreatedTime ||
                    (this.CreatedTime != null &&
                    this.CreatedTime.Equals(input.CreatedTime))
                ) && 
                (
                    this.UpdatedTime == input.UpdatedTime ||
                    (this.UpdatedTime != null &&
                    this.UpdatedTime.Equals(input.UpdatedTime))
                ) && 
                (
                    this.ChannelId == input.ChannelId ||
                    (this.ChannelId != null &&
                    this.ChannelId.Equals(input.ChannelId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.ParentId != null)
                    hashCode = hashCode * 59 + this.ParentId.GetHashCode();
                if (this.CustomerId != null)
                    hashCode = hashCode * 59 + this.CustomerId.GetHashCode();
                if (this.Email != null)
                    hashCode = hashCode * 59 + this.Email.GetHashCode();
                if (this.Currency != null)
                    hashCode = hashCode * 59 + this.Currency.GetHashCode();
                if (this.TaxIncluded != null)
                    hashCode = hashCode * 59 + this.TaxIncluded.GetHashCode();
                if (this.BaseAmount != null)
                    hashCode = hashCode * 59 + this.BaseAmount.GetHashCode();
                if (this.DiscountAmount != null)
                    hashCode = hashCode * 59 + this.DiscountAmount.GetHashCode();
                if (this.CartAmount != null)
                    hashCode = hashCode * 59 + this.CartAmount.GetHashCode();
                if (this.Coupons != null)
                    hashCode = hashCode * 59 + this.Coupons.GetHashCode();
                if (this.Discounts != null)
                    hashCode = hashCode * 59 + this.Discounts.GetHashCode();
                if (this.LineItems != null)
                    hashCode = hashCode * 59 + this.LineItems.GetHashCode();
                if (this.CreatedTime != null)
                    hashCode = hashCode * 59 + this.CreatedTime.GetHashCode();
                if (this.UpdatedTime != null)
                    hashCode = hashCode * 59 + this.UpdatedTime.GetHashCode();
                if (this.ChannelId != null)
                    hashCode = hashCode * 59 + this.ChannelId.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
