/* 
 * Carts
 *
 * Create a cart using BigCommerce cart logic.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = BigCommerce.Client.SwaggerDateConverter;

namespace BigCommerce.Model
{
    /// <summary>
    /// ItemPhysical
    /// </summary>
    [DataContract]
        public partial class ItemPhysical :  IEquatable<ItemPhysical>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ItemPhysical" /> class.
        /// </summary>
        /// <param name="isRequireShipping">isRequireShipping.</param>
        /// <param name="giftWrapping">giftWrapping.</param>
        public ItemPhysical(bool? isRequireShipping = default(bool?), GiftWrapping giftWrapping = default(GiftWrapping))
        {
            this.IsRequireShipping = isRequireShipping;
            this.GiftWrapping = giftWrapping;
        }
        
        /// <summary>
        /// Gets or Sets IsRequireShipping
        /// </summary>
        [DataMember(Name="is_require_shipping", EmitDefaultValue=false)]
        public bool? IsRequireShipping { get; set; }

        /// <summary>
        /// Gets or Sets GiftWrapping
        /// </summary>
        [DataMember(Name="gift_wrapping", EmitDefaultValue=false)]
        public GiftWrapping GiftWrapping { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ItemPhysical {\n");
            sb.Append("  IsRequireShipping: ").Append(IsRequireShipping).Append("\n");
            sb.Append("  GiftWrapping: ").Append(GiftWrapping).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ItemPhysical);
        }

        /// <summary>
        /// Returns true if ItemPhysical instances are equal
        /// </summary>
        /// <param name="input">Instance of ItemPhysical to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ItemPhysical input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.IsRequireShipping == input.IsRequireShipping ||
                    (this.IsRequireShipping != null &&
                    this.IsRequireShipping.Equals(input.IsRequireShipping))
                ) && 
                (
                    this.GiftWrapping == input.GiftWrapping ||
                    (this.GiftWrapping != null &&
                    this.GiftWrapping.Equals(input.GiftWrapping))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.IsRequireShipping != null)
                    hashCode = hashCode * 59 + this.IsRequireShipping.GetHashCode();
                if (this.GiftWrapping != null)
                    hashCode = hashCode * 59 + this.GiftWrapping.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
