/* 
 * Carts
 *
 * Create a cart using BigCommerce cart logic.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = BigCommerce.Client.SwaggerDateConverter;

namespace BigCommerce.Model
{
    /// <summary>
    /// ItemGiftCertificate
    /// </summary>
    [DataContract]
        public partial class ItemGiftCertificate :  IEquatable<ItemGiftCertificate>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ItemGiftCertificate" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="name">GiftCertificate-provided name that will appear in the control panel..</param>
        /// <param name="theme">Currently supports &#x60;Birthday&#x60;, &#x60;Boy&#x60;, &#x60;Celebration&#x60;, &#x60;Christmas&#x60;, &#x60;General&#x60;, and &#x60;Girl&#x60;. (required).</param>
        /// <param name="amount">Value must be between 1.00 and 1,000.00 in the store&#x27;s default currency. (required).</param>
        /// <param name="isTaxable">isTaxable.</param>
        /// <param name="sender">sender (required).</param>
        /// <param name="recipient">recipient (required).</param>
        /// <param name="message">Limited to 200 characters..</param>
        public ItemGiftCertificate(string id = default(string), string name = default(string), string theme = default(string), decimal? amount = default(decimal?), bool? isTaxable = default(bool?), ContactEntity sender = default(ContactEntity), ContactEntity recipient = default(ContactEntity), string message = default(string))
        {
            // to ensure "theme" is required (not null)
            if (theme == null)
            {
                throw new InvalidDataException("theme is a required property for ItemGiftCertificate and cannot be null");
            }
            else
            {
                this.Theme = theme;
            }
            // to ensure "amount" is required (not null)
            if (amount == null)
            {
                throw new InvalidDataException("amount is a required property for ItemGiftCertificate and cannot be null");
            }
            else
            {
                this.Amount = amount;
            }
            // to ensure "sender" is required (not null)
            if (sender == null)
            {
                throw new InvalidDataException("sender is a required property for ItemGiftCertificate and cannot be null");
            }
            else
            {
                this.Sender = sender;
            }
            // to ensure "recipient" is required (not null)
            if (recipient == null)
            {
                throw new InvalidDataException("recipient is a required property for ItemGiftCertificate and cannot be null");
            }
            else
            {
                this.Recipient = recipient;
            }
            this.Id = id;
            this.Name = name;
            this.IsTaxable = isTaxable;
            this.Message = message;
        }
        
        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public string Id { get; set; }

        /// <summary>
        /// GiftCertificate-provided name that will appear in the control panel.
        /// </summary>
        /// <value>GiftCertificate-provided name that will appear in the control panel.</value>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// Currently supports &#x60;Birthday&#x60;, &#x60;Boy&#x60;, &#x60;Celebration&#x60;, &#x60;Christmas&#x60;, &#x60;General&#x60;, and &#x60;Girl&#x60;.
        /// </summary>
        /// <value>Currently supports &#x60;Birthday&#x60;, &#x60;Boy&#x60;, &#x60;Celebration&#x60;, &#x60;Christmas&#x60;, &#x60;General&#x60;, and &#x60;Girl&#x60;.</value>
        [DataMember(Name="theme", EmitDefaultValue=false)]
        public string Theme { get; set; }

        /// <summary>
        /// Value must be between 1.00 and 1,000.00 in the store&#x27;s default currency.
        /// </summary>
        /// <value>Value must be between 1.00 and 1,000.00 in the store&#x27;s default currency.</value>
        [DataMember(Name="amount", EmitDefaultValue=false)]
        public decimal? Amount { get; set; }

        /// <summary>
        /// Gets or Sets IsTaxable
        /// </summary>
        [DataMember(Name="is_taxable", EmitDefaultValue=false)]
        public bool? IsTaxable { get; set; }

        /// <summary>
        /// Gets or Sets Sender
        /// </summary>
        [DataMember(Name="sender", EmitDefaultValue=false)]
        public ContactEntity Sender { get; set; }

        /// <summary>
        /// Gets or Sets Recipient
        /// </summary>
        [DataMember(Name="recipient", EmitDefaultValue=false)]
        public ContactEntity Recipient { get; set; }

        /// <summary>
        /// Limited to 200 characters.
        /// </summary>
        /// <value>Limited to 200 characters.</value>
        [DataMember(Name="message", EmitDefaultValue=false)]
        public string Message { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ItemGiftCertificate {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Theme: ").Append(Theme).Append("\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  IsTaxable: ").Append(IsTaxable).Append("\n");
            sb.Append("  Sender: ").Append(Sender).Append("\n");
            sb.Append("  Recipient: ").Append(Recipient).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ItemGiftCertificate);
        }

        /// <summary>
        /// Returns true if ItemGiftCertificate instances are equal
        /// </summary>
        /// <param name="input">Instance of ItemGiftCertificate to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ItemGiftCertificate input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.Theme == input.Theme ||
                    (this.Theme != null &&
                    this.Theme.Equals(input.Theme))
                ) && 
                (
                    this.Amount == input.Amount ||
                    (this.Amount != null &&
                    this.Amount.Equals(input.Amount))
                ) && 
                (
                    this.IsTaxable == input.IsTaxable ||
                    (this.IsTaxable != null &&
                    this.IsTaxable.Equals(input.IsTaxable))
                ) && 
                (
                    this.Sender == input.Sender ||
                    (this.Sender != null &&
                    this.Sender.Equals(input.Sender))
                ) && 
                (
                    this.Recipient == input.Recipient ||
                    (this.Recipient != null &&
                    this.Recipient.Equals(input.Recipient))
                ) && 
                (
                    this.Message == input.Message ||
                    (this.Message != null &&
                    this.Message.Equals(input.Message))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.Theme != null)
                    hashCode = hashCode * 59 + this.Theme.GetHashCode();
                if (this.Amount != null)
                    hashCode = hashCode * 59 + this.Amount.GetHashCode();
                if (this.IsTaxable != null)
                    hashCode = hashCode * 59 + this.IsTaxable.GetHashCode();
                if (this.Sender != null)
                    hashCode = hashCode * 59 + this.Sender.GetHashCode();
                if (this.Recipient != null)
                    hashCode = hashCode * 59 + this.Recipient.GetHashCode();
                if (this.Message != null)
                    hashCode = hashCode * 59 + this.Message.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
