/* 
 * Widgets
 *
 * Create and manage [widgets](/api-docs/storefront/widgets/widgets-overview), widget templates, regions, and placements.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BigCommerce.Api;
using BigCommerce.Model;
using BigCommerce.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BigCommerce.Test
{
    /// <summary>
    ///  Class for testing NewmodelInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class NewmodelInnerTests
    {
        // TODO uncomment below to declare an instance variable for NewmodelInner
        //private NewmodelInner instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of NewmodelInner
            //instance = new NewmodelInner();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of NewmodelInner
        /// </summary>
        [Test]
        public void NewmodelInnerInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" NewmodelInner
            //Assert.IsInstanceOfType<NewmodelInner> (instance, "variable 'instance' is a NewmodelInner");
        }


        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Label'
        /// </summary>
        [Test]
        public void LabelTest()
        {
            // TODO unit test for the property 'Label'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Default'
        /// </summary>
        [Test]
        public void DefaultTest()
        {
            // TODO unit test for the property 'Default'
        }
        /// <summary>
        /// Test the property 'TypeMeta'
        /// </summary>
        [Test]
        public void TypeMetaTest()
        {
            // TODO unit test for the property 'TypeMeta'
        }
        /// <summary>
        /// Test the property 'Conditional'
        /// </summary>
        [Test]
        public void ConditionalTest()
        {
            // TODO unit test for the property 'Conditional'
        }

    }

}
