/* 
 * Widgets
 *
 * Create and manage [widgets](/api-docs/storefront/widgets/widgets-overview), widget templates, regions, and placements.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Widgets.Api;
using Widgets.Model;
using Widgets.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Widgets.Test
{
    /// <summary>
    ///  Class for testing AllOfinlineResponse200DataItems
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AllOfinlineResponse200DataItemsTests
    {
        // TODO uncomment below to declare an instance variable for AllOfinlineResponse200DataItems
        //private AllOfinlineResponse200DataItems instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AllOfinlineResponse200DataItems
            //instance = new AllOfinlineResponse200DataItems();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AllOfinlineResponse200DataItems
        /// </summary>
        [Test]
        public void AllOfinlineResponse200DataItemsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AllOfinlineResponse200DataItems
            //Assert.IsInstanceOfType<AllOfinlineResponse200DataItems> (instance, "variable 'instance' is a AllOfinlineResponse200DataItems");
        }


        /// <summary>
        /// Test the property 'Uuid'
        /// </summary>
        [Test]
        public void UuidTest()
        {
            // TODO unit test for the property 'Uuid'
        }
        /// <summary>
        /// Test the property 'Kind'
        /// </summary>
        [Test]
        public void KindTest()
        {
            // TODO unit test for the property 'Kind'
        }
        /// <summary>
        /// Test the property 'DateCreated'
        /// </summary>
        [Test]
        public void DateCreatedTest()
        {
            // TODO unit test for the property 'DateCreated'
        }
        /// <summary>
        /// Test the property 'DateModified'
        /// </summary>
        [Test]
        public void DateModifiedTest()
        {
            // TODO unit test for the property 'DateModified'
        }
        /// <summary>
        /// Test the property 'CurrentVersionUuid'
        /// </summary>
        [Test]
        public void CurrentVersionUuidTest()
        {
            // TODO unit test for the property 'CurrentVersionUuid'
        }

    }

}
