/* 
 * Widgets
 *
 * Create and manage [widgets](/api-docs/storefront/widgets/widgets-overview), widget templates, regions, and placements.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Widgets.Api;
using Widgets.Model;
using Widgets.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Widgets.Test
{
    /// <summary>
    ///  Class for testing ThemeRegion
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ThemeRegionTests
    {
        // TODO uncomment below to declare an instance variable for ThemeRegion
        //private ThemeRegion instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ThemeRegion
            //instance = new ThemeRegion();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ThemeRegion
        /// </summary>
        [Test]
        public void ThemeRegionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ThemeRegion
            //Assert.IsInstanceOfType<ThemeRegion> (instance, "variable 'instance' is a ThemeRegion");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

    }

}
