/* 
 * Widgets
 *
 * Create and manage [widgets](/api-docs/storefront/widgets/widgets-overview), widget templates, regions, and placements.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Widgets.Api;
using Widgets.Model;
using Widgets.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Widgets.Test
{
    /// <summary>
    ///  Class for testing WidgetSchemaConditional
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class WidgetSchemaConditionalTests
    {
        // TODO uncomment below to declare an instance variable for WidgetSchemaConditional
        //private WidgetSchemaConditional instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of WidgetSchemaConditional
            //instance = new WidgetSchemaConditional();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WidgetSchemaConditional
        /// </summary>
        [Test]
        public void WidgetSchemaConditionalInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" WidgetSchemaConditional
            //Assert.IsInstanceOfType<WidgetSchemaConditional> (instance, "variable 'instance' is a WidgetSchemaConditional");
        }


        /// <summary>
        /// Test the property 'Key'
        /// </summary>
        [Test]
        public void KeyTest()
        {
            // TODO unit test for the property 'Key'
        }
        /// <summary>
        /// Test the property 'Operator'
        /// </summary>
        [Test]
        public void OperatorTest()
        {
            // TODO unit test for the property 'Operator'
        }
        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Test]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }

    }

}
