/* 
 * Widgets
 *
 * Create and manage [widgets](/api-docs/storefront/widgets/widgets-overview), widget templates, regions, and placements.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Widgets.Api;
using Widgets.Model;
using Widgets.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Widgets.Test
{
    /// <summary>
    ///  Class for testing WidgetTemplatePut1
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class WidgetTemplatePut1Tests
    {
        // TODO uncomment below to declare an instance variable for WidgetTemplatePut1
        //private WidgetTemplatePut1 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of WidgetTemplatePut1
            //instance = new WidgetTemplatePut1();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WidgetTemplatePut1
        /// </summary>
        [Test]
        public void WidgetTemplatePut1InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" WidgetTemplatePut1
            //Assert.IsInstanceOfType<WidgetTemplatePut1> (instance, "variable 'instance' is a WidgetTemplatePut1");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Schema'
        /// </summary>
        [Test]
        public void SchemaTest()
        {
            // TODO unit test for the property 'Schema'
        }
        /// <summary>
        /// Test the property 'Template'
        /// </summary>
        [Test]
        public void TemplateTest()
        {
            // TODO unit test for the property 'Template'
        }

    }

}
