/* 
 * Carts
 *
 * Create a cart using BigCommerce cart logic.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Carts.Client.SwaggerDateConverter;

namespace Carts.Model
{
    /// <summary>
    /// InlineResponse201
    /// </summary>
    [DataContract]
        public partial class InlineResponse201 :  IEquatable<InlineResponse201>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InlineResponse201" /> class.
        /// </summary>
        /// <param name="cartUrl">cartUrl.</param>
        /// <param name="checkoutUrl">checkoutUrl.</param>
        public InlineResponse201(string cartUrl = default(string), string checkoutUrl = default(string))
        {
            this.CartUrl = cartUrl;
            this.CheckoutUrl = checkoutUrl;
        }
        
        /// <summary>
        /// Gets or Sets CartUrl
        /// </summary>
        [DataMember(Name="cart_url", EmitDefaultValue=false)]
        public string CartUrl { get; set; }

        /// <summary>
        /// Gets or Sets CheckoutUrl
        /// </summary>
        [DataMember(Name="checkout_url", EmitDefaultValue=false)]
        public string CheckoutUrl { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InlineResponse201 {\n");
            sb.Append("  CartUrl: ").Append(CartUrl).Append("\n");
            sb.Append("  CheckoutUrl: ").Append(CheckoutUrl).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as InlineResponse201);
        }

        /// <summary>
        /// Returns true if InlineResponse201 instances are equal
        /// </summary>
        /// <param name="input">Instance of InlineResponse201 to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InlineResponse201 input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.CartUrl == input.CartUrl ||
                    (this.CartUrl != null &&
                    this.CartUrl.Equals(input.CartUrl))
                ) && 
                (
                    this.CheckoutUrl == input.CheckoutUrl ||
                    (this.CheckoutUrl != null &&
                    this.CheckoutUrl.Equals(input.CheckoutUrl))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.CartUrl != null)
                    hashCode = hashCode * 59 + this.CartUrl.GetHashCode();
                if (this.CheckoutUrl != null)
                    hashCode = hashCode * 59 + this.CheckoutUrl.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
