/* 
 * Carts
 *
 * Create a cart using BigCommerce cart logic.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Carts.Client.SwaggerDateConverter;

namespace Carts.Model
{
    /// <summary>
    /// Add a custom item to the shoppers cart.  * Custom items are not added to the catalog. * The price should be set to match the store settings for taxes.
    /// </summary>
    [DataContract]
        public partial class ItemCustom :  IEquatable<ItemCustom>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ItemCustom" /> class.
        /// </summary>
        /// <param name="id">Custom item id..</param>
        /// <param name="sku">Custom item sku..</param>
        /// <param name="name">Item&#x27;s product name..</param>
        /// <param name="quantity">Quantity of this item in the cart..</param>
        /// <param name="listPrice">Price of the item. With or without tax depending on the store&#x27;s set up..</param>
        /// <param name="extendedListPrice">Item&#x27;s list price multiplied by quantity..</param>
        public ItemCustom(string id = default(string), string sku = default(string), string name = default(string), decimal? quantity = default(decimal?), decimal? listPrice = default(decimal?), decimal? extendedListPrice = default(decimal?))
        {
            this.Id = id;
            this.Sku = sku;
            this.Name = name;
            this.Quantity = quantity;
            this.ListPrice = listPrice;
            this.ExtendedListPrice = extendedListPrice;
        }
        
        /// <summary>
        /// Custom item id.
        /// </summary>
        /// <value>Custom item id.</value>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public string Id { get; set; }

        /// <summary>
        /// Custom item sku.
        /// </summary>
        /// <value>Custom item sku.</value>
        [DataMember(Name="sku", EmitDefaultValue=false)]
        public string Sku { get; set; }

        /// <summary>
        /// Item&#x27;s product name.
        /// </summary>
        /// <value>Item&#x27;s product name.</value>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// Quantity of this item in the cart.
        /// </summary>
        /// <value>Quantity of this item in the cart.</value>
        [DataMember(Name="quantity", EmitDefaultValue=false)]
        public decimal? Quantity { get; set; }

        /// <summary>
        /// Price of the item. With or without tax depending on the store&#x27;s set up.
        /// </summary>
        /// <value>Price of the item. With or without tax depending on the store&#x27;s set up.</value>
        [DataMember(Name="list_price", EmitDefaultValue=false)]
        public decimal? ListPrice { get; set; }

        /// <summary>
        /// Item&#x27;s list price multiplied by quantity.
        /// </summary>
        /// <value>Item&#x27;s list price multiplied by quantity.</value>
        [DataMember(Name="extended_list_price", EmitDefaultValue=false)]
        public decimal? ExtendedListPrice { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ItemCustom {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Sku: ").Append(Sku).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Quantity: ").Append(Quantity).Append("\n");
            sb.Append("  ListPrice: ").Append(ListPrice).Append("\n");
            sb.Append("  ExtendedListPrice: ").Append(ExtendedListPrice).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ItemCustom);
        }

        /// <summary>
        /// Returns true if ItemCustom instances are equal
        /// </summary>
        /// <param name="input">Instance of ItemCustom to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ItemCustom input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.Sku == input.Sku ||
                    (this.Sku != null &&
                    this.Sku.Equals(input.Sku))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.Quantity == input.Quantity ||
                    (this.Quantity != null &&
                    this.Quantity.Equals(input.Quantity))
                ) && 
                (
                    this.ListPrice == input.ListPrice ||
                    (this.ListPrice != null &&
                    this.ListPrice.Equals(input.ListPrice))
                ) && 
                (
                    this.ExtendedListPrice == input.ExtendedListPrice ||
                    (this.ExtendedListPrice != null &&
                    this.ExtendedListPrice.Equals(input.ExtendedListPrice))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.Sku != null)
                    hashCode = hashCode * 59 + this.Sku.GetHashCode();
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.Quantity != null)
                    hashCode = hashCode * 59 + this.Quantity.GetHashCode();
                if (this.ListPrice != null)
                    hashCode = hashCode * 59 + this.ListPrice.GetHashCode();
                if (this.ExtendedListPrice != null)
                    hashCode = hashCode * 59 + this.ExtendedListPrice.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
