/* 
 * Store Information
 *
 * Get Store Information endpoint, manage store profile settings.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BigCommerce.Api;
using BigCommerce.Model;
using BigCommerce.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BigCommerce.Test
{
    /// <summary>
    ///  Class for testing StoreInformationFeatures
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class StoreInformationFeaturesTests
    {
        // TODO uncomment below to declare an instance variable for StoreInformationFeatures
        //private StoreInformationFeatures instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of StoreInformationFeatures
            //instance = new StoreInformationFeatures();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of StoreInformationFeatures
        /// </summary>
        [Test]
        public void StoreInformationFeaturesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" StoreInformationFeatures
            //Assert.IsInstanceOfType<StoreInformationFeatures> (instance, "variable 'instance' is a StoreInformationFeatures");
        }


        /// <summary>
        /// Test the property 'StencilEnabled'
        /// </summary>
        [Test]
        public void StencilEnabledTest()
        {
            // TODO unit test for the property 'StencilEnabled'
        }
        /// <summary>
        /// Test the property 'SitewidehttpsEnabled'
        /// </summary>
        [Test]
        public void SitewidehttpsEnabledTest()
        {
            // TODO unit test for the property 'SitewidehttpsEnabled'
        }
        /// <summary>
        /// Test the property 'FacebookCatalogId'
        /// </summary>
        [Test]
        public void FacebookCatalogIdTest()
        {
            // TODO unit test for the property 'FacebookCatalogId'
        }
        /// <summary>
        /// Test the property 'CheckoutType'
        /// </summary>
        [Test]
        public void CheckoutTypeTest()
        {
            // TODO unit test for the property 'CheckoutType'
        }

    }

}
