/* 
 * Carts
 *
 * Create a cart using BigCommerce cart logic.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using Carts.Client;
using Carts.Model;

namespace Carts.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public interface ICartApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Create a Cart
        /// </summary>
        /// <remarks>
        /// Creates a **Cart**.   **Required Fields** |Field|Details| |-|-| |&#x60;line_items&#x60;||  |&#x60;custom_items&#x60;|Only required if adding a custom item to the cart.| |&#x60;gift_certificates&#x60;|Only required if adding a gift certificate to the cart.|  **Usage Notes**  * A **cart** &#x60;id&#x60; (UUID) is returned in the response. * A **cart** &#x60;id&#x60; is the same as a **checkout** &#x60;id&#x60;. * A cart can be created by adding an existing **catalog item** or a **custom item**. * Carts are valid for **30 days** from the **last modification** (this includes creating the cart or editing the cart). * If a product has modifiers, omit the &#x60;variant_id&#x60; and instead use the &#x60;option_selections&#x60; array to describe both the **variant** and the **modifier** selections. * Redirect URLs can only be generated from carts created using the **Server-to-Server Carts API**.  * To get cart &#x60;redirect_urls&#x60; in the response, append the following query parameter to the request URL: &#x60;include&#x3D;redirect_urls&#x60;. * To restore a cart that was created by a shopper or via the Storefront Cart API, first recreate the cart using the Server to Server Cart API.
        /// </remarks>
        /// <exception cref="Carts.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">**Examples:**

1. Creating a cart by adding a simple product (a product without option selections).
2. Creating a cart with a variant. This works when a product can be specified purely by a variant, without any other required options.
3. Creating a cart with a variant, a checkbox, and a picklist modifier added.
4. Creating a cart using a custom item.</param>
        /// <param name="accept"></param>
        /// <param name="contentType"></param>
        /// <param name="include">* &#x60;redirect_urls&#x60;: Create a direct link to a Cart. This can be used during the /POST request for Carts. * &#x60;line_items.physical_items.options&#x60;: The Cart returns an abbreviated result. Use this to return physical items product options. Can also be used in a /POST to have the extended Cart object return. * &#x60;line_items.digital_items.options&#x60;: The Cart returns an abbreviated result. Use this to return digital items product options.  Can also be used in a /POST to have the extended Cart object return. (optional)</param>
        /// <returns>CartFull1</returns>
        CartFull1 CreateACart (CartCreatePostData body, string accept, string contentType, string include = null);

        /// <summary>
        /// Create a Cart
        /// </summary>
        /// <remarks>
        /// Creates a **Cart**.   **Required Fields** |Field|Details| |-|-| |&#x60;line_items&#x60;||  |&#x60;custom_items&#x60;|Only required if adding a custom item to the cart.| |&#x60;gift_certificates&#x60;|Only required if adding a gift certificate to the cart.|  **Usage Notes**  * A **cart** &#x60;id&#x60; (UUID) is returned in the response. * A **cart** &#x60;id&#x60; is the same as a **checkout** &#x60;id&#x60;. * A cart can be created by adding an existing **catalog item** or a **custom item**. * Carts are valid for **30 days** from the **last modification** (this includes creating the cart or editing the cart). * If a product has modifiers, omit the &#x60;variant_id&#x60; and instead use the &#x60;option_selections&#x60; array to describe both the **variant** and the **modifier** selections. * Redirect URLs can only be generated from carts created using the **Server-to-Server Carts API**.  * To get cart &#x60;redirect_urls&#x60; in the response, append the following query parameter to the request URL: &#x60;include&#x3D;redirect_urls&#x60;. * To restore a cart that was created by a shopper or via the Storefront Cart API, first recreate the cart using the Server to Server Cart API.
        /// </remarks>
        /// <exception cref="Carts.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">**Examples:**

1. Creating a cart by adding a simple product (a product without option selections).
2. Creating a cart with a variant. This works when a product can be specified purely by a variant, without any other required options.
3. Creating a cart with a variant, a checkbox, and a picklist modifier added.
4. Creating a cart using a custom item.</param>
        /// <param name="accept"></param>
        /// <param name="contentType"></param>
        /// <param name="include">* &#x60;redirect_urls&#x60;: Create a direct link to a Cart. This can be used during the /POST request for Carts. * &#x60;line_items.physical_items.options&#x60;: The Cart returns an abbreviated result. Use this to return physical items product options. Can also be used in a /POST to have the extended Cart object return. * &#x60;line_items.digital_items.options&#x60;: The Cart returns an abbreviated result. Use this to return digital items product options.  Can also be used in a /POST to have the extended Cart object return. (optional)</param>
        /// <returns>ApiResponse of CartFull1</returns>
        ApiResponse<CartFull1> CreateACartWithHttpInfo (CartCreatePostData body, string accept, string contentType, string include = null);
        /// <summary>
        /// Delete a Cart
        /// </summary>
        /// <remarks>
        /// Deletes a *Cart*. Once a *Cart* has been deleted it can not be recovered.
        /// </remarks>
        /// <exception cref="Carts.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cartId">This cart&#x27;s unique ID.</param>
        /// <param name="accept"></param>
        /// <param name="contentType"></param>
        /// <returns></returns>
        void DeleteACart (string cartId, string accept, string contentType);

        /// <summary>
        /// Delete a Cart
        /// </summary>
        /// <remarks>
        /// Deletes a *Cart*. Once a *Cart* has been deleted it can not be recovered.
        /// </remarks>
        /// <exception cref="Carts.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cartId">This cart&#x27;s unique ID.</param>
        /// <param name="accept"></param>
        /// <param name="contentType"></param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> DeleteACartWithHttpInfo (string cartId, string accept, string contentType);
        /// <summary>
        /// Get a Cart
        /// </summary>
        /// <remarks>
        /// Returns a stores *Cart*.
        /// </remarks>
        /// <exception cref="Carts.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cartId">The identifier of a specific cart.</param>
        /// <param name="accept"></param>
        /// <param name="contentType"></param>
        /// <param name="include">* &#x60;redirect_urls&#x60;: Create a direct link to a Cart. This can be used during the /POST request for Carts. * &#x60;line_items.physical_items.options&#x60;: The Cart returns an abbreviated result. Use this to return physical items product options. Can also be used in a /POST to have the extended Cart object return. * &#x60;line_items.digital_items.options&#x60;: The Cart returns an abbreviated result. Use this to return digital items product options.  Can also be used in a /POST to have the extended Cart object return. (optional)</param>
        /// <returns>CartFull1</returns>
        CartFull1 GetACart (string cartId, string accept, string contentType, string include = null);

        /// <summary>
        /// Get a Cart
        /// </summary>
        /// <remarks>
        /// Returns a stores *Cart*.
        /// </remarks>
        /// <exception cref="Carts.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cartId">The identifier of a specific cart.</param>
        /// <param name="accept"></param>
        /// <param name="contentType"></param>
        /// <param name="include">* &#x60;redirect_urls&#x60;: Create a direct link to a Cart. This can be used during the /POST request for Carts. * &#x60;line_items.physical_items.options&#x60;: The Cart returns an abbreviated result. Use this to return physical items product options. Can also be used in a /POST to have the extended Cart object return. * &#x60;line_items.digital_items.options&#x60;: The Cart returns an abbreviated result. Use this to return digital items product options.  Can also be used in a /POST to have the extended Cart object return. (optional)</param>
        /// <returns>ApiResponse of CartFull1</returns>
        ApiResponse<CartFull1> GetACartWithHttpInfo (string cartId, string accept, string contentType, string include = null);
        /// <summary>
        /// Update Customer ID
        /// </summary>
        /// <remarks>
        /// Updates a *Carts* &#x60;customer_id&#x60;.  **Notes**  Changing the *Cart* &#x60;customer_id&#x60; will remove any promotions or shipping on the *Cart*. These are tied to the customer depending on cart conditions and any customer groups. 
        /// </remarks>
        /// <exception cref="Carts.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="accept"></param>
        /// <param name="contentType"></param>
        /// <param name="cartId"></param>
        /// <param name="include">* &#x60;redirect_urls&#x60;: Create a direct link to a Cart. This can be used during the /POST request for Carts. * &#x60;line_items.physical_items.options&#x60;: The Cart returns an abbreviated result. Use this to return physical items product options. Can also be used in a /POST to have the extended Cart object return. * &#x60;line_items.digital_items.options&#x60;: The Cart returns an abbreviated result. Use this to return digital items product options.  Can also be used in a /POST to have the extended Cart object return. (optional)</param>
        /// <returns>CartFull1</returns>
        CartFull1 UpdateACart (CartUpdatePutRequestData body, string accept, string contentType, string cartId, string include = null);

        /// <summary>
        /// Update Customer ID
        /// </summary>
        /// <remarks>
        /// Updates a *Carts* &#x60;customer_id&#x60;.  **Notes**  Changing the *Cart* &#x60;customer_id&#x60; will remove any promotions or shipping on the *Cart*. These are tied to the customer depending on cart conditions and any customer groups. 
        /// </remarks>
        /// <exception cref="Carts.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="accept"></param>
        /// <param name="contentType"></param>
        /// <param name="cartId"></param>
        /// <param name="include">* &#x60;redirect_urls&#x60;: Create a direct link to a Cart. This can be used during the /POST request for Carts. * &#x60;line_items.physical_items.options&#x60;: The Cart returns an abbreviated result. Use this to return physical items product options. Can also be used in a /POST to have the extended Cart object return. * &#x60;line_items.digital_items.options&#x60;: The Cart returns an abbreviated result. Use this to return digital items product options.  Can also be used in a /POST to have the extended Cart object return. (optional)</param>
        /// <returns>ApiResponse of CartFull1</returns>
        ApiResponse<CartFull1> UpdateACartWithHttpInfo (CartUpdatePutRequestData body, string accept, string contentType, string cartId, string include = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Create a Cart
        /// </summary>
        /// <remarks>
        /// Creates a **Cart**.   **Required Fields** |Field|Details| |-|-| |&#x60;line_items&#x60;||  |&#x60;custom_items&#x60;|Only required if adding a custom item to the cart.| |&#x60;gift_certificates&#x60;|Only required if adding a gift certificate to the cart.|  **Usage Notes**  * A **cart** &#x60;id&#x60; (UUID) is returned in the response. * A **cart** &#x60;id&#x60; is the same as a **checkout** &#x60;id&#x60;. * A cart can be created by adding an existing **catalog item** or a **custom item**. * Carts are valid for **30 days** from the **last modification** (this includes creating the cart or editing the cart). * If a product has modifiers, omit the &#x60;variant_id&#x60; and instead use the &#x60;option_selections&#x60; array to describe both the **variant** and the **modifier** selections. * Redirect URLs can only be generated from carts created using the **Server-to-Server Carts API**.  * To get cart &#x60;redirect_urls&#x60; in the response, append the following query parameter to the request URL: &#x60;include&#x3D;redirect_urls&#x60;. * To restore a cart that was created by a shopper or via the Storefront Cart API, first recreate the cart using the Server to Server Cart API.
        /// </remarks>
        /// <exception cref="Carts.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">**Examples:**

1. Creating a cart by adding a simple product (a product without option selections).
2. Creating a cart with a variant. This works when a product can be specified purely by a variant, without any other required options.
3. Creating a cart with a variant, a checkbox, and a picklist modifier added.
4. Creating a cart using a custom item.</param>
        /// <param name="accept"></param>
        /// <param name="contentType"></param>
        /// <param name="include">* &#x60;redirect_urls&#x60;: Create a direct link to a Cart. This can be used during the /POST request for Carts. * &#x60;line_items.physical_items.options&#x60;: The Cart returns an abbreviated result. Use this to return physical items product options. Can also be used in a /POST to have the extended Cart object return. * &#x60;line_items.digital_items.options&#x60;: The Cart returns an abbreviated result. Use this to return digital items product options.  Can also be used in a /POST to have the extended Cart object return. (optional)</param>
        /// <returns>Task of CartFull1</returns>
        System.Threading.Tasks.Task<CartFull1> CreateACartAsync (CartCreatePostData body, string accept, string contentType, string include = null);

        /// <summary>
        /// Create a Cart
        /// </summary>
        /// <remarks>
        /// Creates a **Cart**.   **Required Fields** |Field|Details| |-|-| |&#x60;line_items&#x60;||  |&#x60;custom_items&#x60;|Only required if adding a custom item to the cart.| |&#x60;gift_certificates&#x60;|Only required if adding a gift certificate to the cart.|  **Usage Notes**  * A **cart** &#x60;id&#x60; (UUID) is returned in the response. * A **cart** &#x60;id&#x60; is the same as a **checkout** &#x60;id&#x60;. * A cart can be created by adding an existing **catalog item** or a **custom item**. * Carts are valid for **30 days** from the **last modification** (this includes creating the cart or editing the cart). * If a product has modifiers, omit the &#x60;variant_id&#x60; and instead use the &#x60;option_selections&#x60; array to describe both the **variant** and the **modifier** selections. * Redirect URLs can only be generated from carts created using the **Server-to-Server Carts API**.  * To get cart &#x60;redirect_urls&#x60; in the response, append the following query parameter to the request URL: &#x60;include&#x3D;redirect_urls&#x60;. * To restore a cart that was created by a shopper or via the Storefront Cart API, first recreate the cart using the Server to Server Cart API.
        /// </remarks>
        /// <exception cref="Carts.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">**Examples:**

1. Creating a cart by adding a simple product (a product without option selections).
2. Creating a cart with a variant. This works when a product can be specified purely by a variant, without any other required options.
3. Creating a cart with a variant, a checkbox, and a picklist modifier added.
4. Creating a cart using a custom item.</param>
        /// <param name="accept"></param>
        /// <param name="contentType"></param>
        /// <param name="include">* &#x60;redirect_urls&#x60;: Create a direct link to a Cart. This can be used during the /POST request for Carts. * &#x60;line_items.physical_items.options&#x60;: The Cart returns an abbreviated result. Use this to return physical items product options. Can also be used in a /POST to have the extended Cart object return. * &#x60;line_items.digital_items.options&#x60;: The Cart returns an abbreviated result. Use this to return digital items product options.  Can also be used in a /POST to have the extended Cart object return. (optional)</param>
        /// <returns>Task of ApiResponse (CartFull1)</returns>
        System.Threading.Tasks.Task<ApiResponse<CartFull1>> CreateACartAsyncWithHttpInfo (CartCreatePostData body, string accept, string contentType, string include = null);
        /// <summary>
        /// Delete a Cart
        /// </summary>
        /// <remarks>
        /// Deletes a *Cart*. Once a *Cart* has been deleted it can not be recovered.
        /// </remarks>
        /// <exception cref="Carts.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cartId">This cart&#x27;s unique ID.</param>
        /// <param name="accept"></param>
        /// <param name="contentType"></param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task DeleteACartAsync (string cartId, string accept, string contentType);

        /// <summary>
        /// Delete a Cart
        /// </summary>
        /// <remarks>
        /// Deletes a *Cart*. Once a *Cart* has been deleted it can not be recovered.
        /// </remarks>
        /// <exception cref="Carts.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cartId">This cart&#x27;s unique ID.</param>
        /// <param name="accept"></param>
        /// <param name="contentType"></param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> DeleteACartAsyncWithHttpInfo (string cartId, string accept, string contentType);
        /// <summary>
        /// Get a Cart
        /// </summary>
        /// <remarks>
        /// Returns a stores *Cart*.
        /// </remarks>
        /// <exception cref="Carts.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cartId">The identifier of a specific cart.</param>
        /// <param name="accept"></param>
        /// <param name="contentType"></param>
        /// <param name="include">* &#x60;redirect_urls&#x60;: Create a direct link to a Cart. This can be used during the /POST request for Carts. * &#x60;line_items.physical_items.options&#x60;: The Cart returns an abbreviated result. Use this to return physical items product options. Can also be used in a /POST to have the extended Cart object return. * &#x60;line_items.digital_items.options&#x60;: The Cart returns an abbreviated result. Use this to return digital items product options.  Can also be used in a /POST to have the extended Cart object return. (optional)</param>
        /// <returns>Task of CartFull1</returns>
        System.Threading.Tasks.Task<CartFull1> GetACartAsync (string cartId, string accept, string contentType, string include = null);

        /// <summary>
        /// Get a Cart
        /// </summary>
        /// <remarks>
        /// Returns a stores *Cart*.
        /// </remarks>
        /// <exception cref="Carts.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cartId">The identifier of a specific cart.</param>
        /// <param name="accept"></param>
        /// <param name="contentType"></param>
        /// <param name="include">* &#x60;redirect_urls&#x60;: Create a direct link to a Cart. This can be used during the /POST request for Carts. * &#x60;line_items.physical_items.options&#x60;: The Cart returns an abbreviated result. Use this to return physical items product options. Can also be used in a /POST to have the extended Cart object return. * &#x60;line_items.digital_items.options&#x60;: The Cart returns an abbreviated result. Use this to return digital items product options.  Can also be used in a /POST to have the extended Cart object return. (optional)</param>
        /// <returns>Task of ApiResponse (CartFull1)</returns>
        System.Threading.Tasks.Task<ApiResponse<CartFull1>> GetACartAsyncWithHttpInfo (string cartId, string accept, string contentType, string include = null);
        /// <summary>
        /// Update Customer ID
        /// </summary>
        /// <remarks>
        /// Updates a *Carts* &#x60;customer_id&#x60;.  **Notes**  Changing the *Cart* &#x60;customer_id&#x60; will remove any promotions or shipping on the *Cart*. These are tied to the customer depending on cart conditions and any customer groups. 
        /// </remarks>
        /// <exception cref="Carts.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="accept"></param>
        /// <param name="contentType"></param>
        /// <param name="cartId"></param>
        /// <param name="include">* &#x60;redirect_urls&#x60;: Create a direct link to a Cart. This can be used during the /POST request for Carts. * &#x60;line_items.physical_items.options&#x60;: The Cart returns an abbreviated result. Use this to return physical items product options. Can also be used in a /POST to have the extended Cart object return. * &#x60;line_items.digital_items.options&#x60;: The Cart returns an abbreviated result. Use this to return digital items product options.  Can also be used in a /POST to have the extended Cart object return. (optional)</param>
        /// <returns>Task of CartFull1</returns>
        System.Threading.Tasks.Task<CartFull1> UpdateACartAsync (CartUpdatePutRequestData body, string accept, string contentType, string cartId, string include = null);

        /// <summary>
        /// Update Customer ID
        /// </summary>
        /// <remarks>
        /// Updates a *Carts* &#x60;customer_id&#x60;.  **Notes**  Changing the *Cart* &#x60;customer_id&#x60; will remove any promotions or shipping on the *Cart*. These are tied to the customer depending on cart conditions and any customer groups. 
        /// </remarks>
        /// <exception cref="Carts.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="accept"></param>
        /// <param name="contentType"></param>
        /// <param name="cartId"></param>
        /// <param name="include">* &#x60;redirect_urls&#x60;: Create a direct link to a Cart. This can be used during the /POST request for Carts. * &#x60;line_items.physical_items.options&#x60;: The Cart returns an abbreviated result. Use this to return physical items product options. Can also be used in a /POST to have the extended Cart object return. * &#x60;line_items.digital_items.options&#x60;: The Cart returns an abbreviated result. Use this to return digital items product options.  Can also be used in a /POST to have the extended Cart object return. (optional)</param>
        /// <returns>Task of ApiResponse (CartFull1)</returns>
        System.Threading.Tasks.Task<ApiResponse<CartFull1>> UpdateACartAsyncWithHttpInfo (CartUpdatePutRequestData body, string accept, string contentType, string cartId, string include = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public partial class CartApi : ICartApi
    {
        private Carts.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="CartApi"/> class.
        /// </summary>
        /// <returns></returns>
        public CartApi(String basePath)
        {
            this.Configuration = new Carts.Client.Configuration { BasePath = basePath };

            ExceptionFactory = Carts.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CartApi"/> class
        /// </summary>
        /// <returns></returns>
        public CartApi()
        {
            this.Configuration = Carts.Client.Configuration.Default;

            ExceptionFactory = Carts.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CartApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public CartApi(Carts.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Carts.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = Carts.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Carts.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Carts.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Create a Cart Creates a **Cart**.   **Required Fields** |Field|Details| |-|-| |&#x60;line_items&#x60;||  |&#x60;custom_items&#x60;|Only required if adding a custom item to the cart.| |&#x60;gift_certificates&#x60;|Only required if adding a gift certificate to the cart.|  **Usage Notes**  * A **cart** &#x60;id&#x60; (UUID) is returned in the response. * A **cart** &#x60;id&#x60; is the same as a **checkout** &#x60;id&#x60;. * A cart can be created by adding an existing **catalog item** or a **custom item**. * Carts are valid for **30 days** from the **last modification** (this includes creating the cart or editing the cart). * If a product has modifiers, omit the &#x60;variant_id&#x60; and instead use the &#x60;option_selections&#x60; array to describe both the **variant** and the **modifier** selections. * Redirect URLs can only be generated from carts created using the **Server-to-Server Carts API**.  * To get cart &#x60;redirect_urls&#x60; in the response, append the following query parameter to the request URL: &#x60;include&#x3D;redirect_urls&#x60;. * To restore a cart that was created by a shopper or via the Storefront Cart API, first recreate the cart using the Server to Server Cart API.
        /// </summary>
        /// <exception cref="Carts.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">**Examples:**

1. Creating a cart by adding a simple product (a product without option selections).
2. Creating a cart with a variant. This works when a product can be specified purely by a variant, without any other required options.
3. Creating a cart with a variant, a checkbox, and a picklist modifier added.
4. Creating a cart using a custom item.</param>
        /// <param name="accept"></param>
        /// <param name="contentType"></param>
        /// <param name="include">* &#x60;redirect_urls&#x60;: Create a direct link to a Cart. This can be used during the /POST request for Carts. * &#x60;line_items.physical_items.options&#x60;: The Cart returns an abbreviated result. Use this to return physical items product options. Can also be used in a /POST to have the extended Cart object return. * &#x60;line_items.digital_items.options&#x60;: The Cart returns an abbreviated result. Use this to return digital items product options.  Can also be used in a /POST to have the extended Cart object return. (optional)</param>
        /// <returns>CartFull1</returns>
        public CartFull1 CreateACart (CartCreatePostData body, string accept, string contentType, string include = null)
        {
             ApiResponse<CartFull1> localVarResponse = CreateACartWithHttpInfo(body, accept, contentType, include);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Create a Cart Creates a **Cart**.   **Required Fields** |Field|Details| |-|-| |&#x60;line_items&#x60;||  |&#x60;custom_items&#x60;|Only required if adding a custom item to the cart.| |&#x60;gift_certificates&#x60;|Only required if adding a gift certificate to the cart.|  **Usage Notes**  * A **cart** &#x60;id&#x60; (UUID) is returned in the response. * A **cart** &#x60;id&#x60; is the same as a **checkout** &#x60;id&#x60;. * A cart can be created by adding an existing **catalog item** or a **custom item**. * Carts are valid for **30 days** from the **last modification** (this includes creating the cart or editing the cart). * If a product has modifiers, omit the &#x60;variant_id&#x60; and instead use the &#x60;option_selections&#x60; array to describe both the **variant** and the **modifier** selections. * Redirect URLs can only be generated from carts created using the **Server-to-Server Carts API**.  * To get cart &#x60;redirect_urls&#x60; in the response, append the following query parameter to the request URL: &#x60;include&#x3D;redirect_urls&#x60;. * To restore a cart that was created by a shopper or via the Storefront Cart API, first recreate the cart using the Server to Server Cart API.
        /// </summary>
        /// <exception cref="Carts.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">**Examples:**

1. Creating a cart by adding a simple product (a product without option selections).
2. Creating a cart with a variant. This works when a product can be specified purely by a variant, without any other required options.
3. Creating a cart with a variant, a checkbox, and a picklist modifier added.
4. Creating a cart using a custom item.</param>
        /// <param name="accept"></param>
        /// <param name="contentType"></param>
        /// <param name="include">* &#x60;redirect_urls&#x60;: Create a direct link to a Cart. This can be used during the /POST request for Carts. * &#x60;line_items.physical_items.options&#x60;: The Cart returns an abbreviated result. Use this to return physical items product options. Can also be used in a /POST to have the extended Cart object return. * &#x60;line_items.digital_items.options&#x60;: The Cart returns an abbreviated result. Use this to return digital items product options.  Can also be used in a /POST to have the extended Cart object return. (optional)</param>
        /// <returns>ApiResponse of CartFull1</returns>
        public ApiResponse< CartFull1 > CreateACartWithHttpInfo (CartCreatePostData body, string accept, string contentType, string include = null)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling CartApi->CreateACart");
            // verify the required parameter 'accept' is set
            if (accept == null)
                throw new ApiException(400, "Missing required parameter 'accept' when calling CartApi->CreateACart");
            // verify the required parameter 'contentType' is set
            if (contentType == null)
                throw new ApiException(400, "Missing required parameter 'contentType' when calling CartApi->CreateACart");

            var localVarPath = "/carts";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (include != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "include", include)); // query parameter
            if (accept != null) localVarHeaderParams.Add("Accept", this.Configuration.ApiClient.ParameterToString(accept)); // header parameter
            if (contentType != null) localVarHeaderParams.Add("Content-Type", this.Configuration.ApiClient.ParameterToString(contentType)); // header parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }
            // authentication (X-Auth-Token) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-Auth-Token")))
            {
                localVarHeaderParams["X-Auth-Token"] = this.Configuration.GetApiKeyWithPrefix("X-Auth-Token");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CreateACart", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<CartFull1>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (CartFull1) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(CartFull1)));
        }

        /// <summary>
        /// Create a Cart Creates a **Cart**.   **Required Fields** |Field|Details| |-|-| |&#x60;line_items&#x60;||  |&#x60;custom_items&#x60;|Only required if adding a custom item to the cart.| |&#x60;gift_certificates&#x60;|Only required if adding a gift certificate to the cart.|  **Usage Notes**  * A **cart** &#x60;id&#x60; (UUID) is returned in the response. * A **cart** &#x60;id&#x60; is the same as a **checkout** &#x60;id&#x60;. * A cart can be created by adding an existing **catalog item** or a **custom item**. * Carts are valid for **30 days** from the **last modification** (this includes creating the cart or editing the cart). * If a product has modifiers, omit the &#x60;variant_id&#x60; and instead use the &#x60;option_selections&#x60; array to describe both the **variant** and the **modifier** selections. * Redirect URLs can only be generated from carts created using the **Server-to-Server Carts API**.  * To get cart &#x60;redirect_urls&#x60; in the response, append the following query parameter to the request URL: &#x60;include&#x3D;redirect_urls&#x60;. * To restore a cart that was created by a shopper or via the Storefront Cart API, first recreate the cart using the Server to Server Cart API.
        /// </summary>
        /// <exception cref="Carts.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">**Examples:**

1. Creating a cart by adding a simple product (a product without option selections).
2. Creating a cart with a variant. This works when a product can be specified purely by a variant, without any other required options.
3. Creating a cart with a variant, a checkbox, and a picklist modifier added.
4. Creating a cart using a custom item.</param>
        /// <param name="accept"></param>
        /// <param name="contentType"></param>
        /// <param name="include">* &#x60;redirect_urls&#x60;: Create a direct link to a Cart. This can be used during the /POST request for Carts. * &#x60;line_items.physical_items.options&#x60;: The Cart returns an abbreviated result. Use this to return physical items product options. Can also be used in a /POST to have the extended Cart object return. * &#x60;line_items.digital_items.options&#x60;: The Cart returns an abbreviated result. Use this to return digital items product options.  Can also be used in a /POST to have the extended Cart object return. (optional)</param>
        /// <returns>Task of CartFull1</returns>
        public async System.Threading.Tasks.Task<CartFull1> CreateACartAsync (CartCreatePostData body, string accept, string contentType, string include = null)
        {
             ApiResponse<CartFull1> localVarResponse = await CreateACartAsyncWithHttpInfo(body, accept, contentType, include);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Create a Cart Creates a **Cart**.   **Required Fields** |Field|Details| |-|-| |&#x60;line_items&#x60;||  |&#x60;custom_items&#x60;|Only required if adding a custom item to the cart.| |&#x60;gift_certificates&#x60;|Only required if adding a gift certificate to the cart.|  **Usage Notes**  * A **cart** &#x60;id&#x60; (UUID) is returned in the response. * A **cart** &#x60;id&#x60; is the same as a **checkout** &#x60;id&#x60;. * A cart can be created by adding an existing **catalog item** or a **custom item**. * Carts are valid for **30 days** from the **last modification** (this includes creating the cart or editing the cart). * If a product has modifiers, omit the &#x60;variant_id&#x60; and instead use the &#x60;option_selections&#x60; array to describe both the **variant** and the **modifier** selections. * Redirect URLs can only be generated from carts created using the **Server-to-Server Carts API**.  * To get cart &#x60;redirect_urls&#x60; in the response, append the following query parameter to the request URL: &#x60;include&#x3D;redirect_urls&#x60;. * To restore a cart that was created by a shopper or via the Storefront Cart API, first recreate the cart using the Server to Server Cart API.
        /// </summary>
        /// <exception cref="Carts.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">**Examples:**

1. Creating a cart by adding a simple product (a product without option selections).
2. Creating a cart with a variant. This works when a product can be specified purely by a variant, without any other required options.
3. Creating a cart with a variant, a checkbox, and a picklist modifier added.
4. Creating a cart using a custom item.</param>
        /// <param name="accept"></param>
        /// <param name="contentType"></param>
        /// <param name="include">* &#x60;redirect_urls&#x60;: Create a direct link to a Cart. This can be used during the /POST request for Carts. * &#x60;line_items.physical_items.options&#x60;: The Cart returns an abbreviated result. Use this to return physical items product options. Can also be used in a /POST to have the extended Cart object return. * &#x60;line_items.digital_items.options&#x60;: The Cart returns an abbreviated result. Use this to return digital items product options.  Can also be used in a /POST to have the extended Cart object return. (optional)</param>
        /// <returns>Task of ApiResponse (CartFull1)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<CartFull1>> CreateACartAsyncWithHttpInfo (CartCreatePostData body, string accept, string contentType, string include = null)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling CartApi->CreateACart");
            // verify the required parameter 'accept' is set
            if (accept == null)
                throw new ApiException(400, "Missing required parameter 'accept' when calling CartApi->CreateACart");
            // verify the required parameter 'contentType' is set
            if (contentType == null)
                throw new ApiException(400, "Missing required parameter 'contentType' when calling CartApi->CreateACart");

            var localVarPath = "/carts";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (include != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "include", include)); // query parameter
            if (accept != null) localVarHeaderParams.Add("Accept", this.Configuration.ApiClient.ParameterToString(accept)); // header parameter
            if (contentType != null) localVarHeaderParams.Add("Content-Type", this.Configuration.ApiClient.ParameterToString(contentType)); // header parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }
            // authentication (X-Auth-Token) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-Auth-Token")))
            {
                localVarHeaderParams["X-Auth-Token"] = this.Configuration.GetApiKeyWithPrefix("X-Auth-Token");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CreateACart", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<CartFull1>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (CartFull1) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(CartFull1)));
        }

        /// <summary>
        /// Delete a Cart Deletes a *Cart*. Once a *Cart* has been deleted it can not be recovered.
        /// </summary>
        /// <exception cref="Carts.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cartId">This cart&#x27;s unique ID.</param>
        /// <param name="accept"></param>
        /// <param name="contentType"></param>
        /// <returns></returns>
        public void DeleteACart (string cartId, string accept, string contentType)
        {
             DeleteACartWithHttpInfo(cartId, accept, contentType);
        }

        /// <summary>
        /// Delete a Cart Deletes a *Cart*. Once a *Cart* has been deleted it can not be recovered.
        /// </summary>
        /// <exception cref="Carts.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cartId">This cart&#x27;s unique ID.</param>
        /// <param name="accept"></param>
        /// <param name="contentType"></param>
        /// <returns>ApiResponse of Object(void)</returns>
        public ApiResponse<Object> DeleteACartWithHttpInfo (string cartId, string accept, string contentType)
        {
            // verify the required parameter 'cartId' is set
            if (cartId == null)
                throw new ApiException(400, "Missing required parameter 'cartId' when calling CartApi->DeleteACart");
            // verify the required parameter 'accept' is set
            if (accept == null)
                throw new ApiException(400, "Missing required parameter 'accept' when calling CartApi->DeleteACart");
            // verify the required parameter 'contentType' is set
            if (contentType == null)
                throw new ApiException(400, "Missing required parameter 'contentType' when calling CartApi->DeleteACart");

            var localVarPath = "/carts/{cartId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (cartId != null) localVarPathParams.Add("cartId", this.Configuration.ApiClient.ParameterToString(cartId)); // path parameter
            if (accept != null) localVarHeaderParams.Add("Accept", this.Configuration.ApiClient.ParameterToString(accept)); // header parameter
            if (contentType != null) localVarHeaderParams.Add("Content-Type", this.Configuration.ApiClient.ParameterToString(contentType)); // header parameter
            // authentication (X-Auth-Token) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-Auth-Token")))
            {
                localVarHeaderParams["X-Auth-Token"] = this.Configuration.GetApiKeyWithPrefix("X-Auth-Token");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DeleteACart", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                null);
        }

        /// <summary>
        /// Delete a Cart Deletes a *Cart*. Once a *Cart* has been deleted it can not be recovered.
        /// </summary>
        /// <exception cref="Carts.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cartId">This cart&#x27;s unique ID.</param>
        /// <param name="accept"></param>
        /// <param name="contentType"></param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task DeleteACartAsync (string cartId, string accept, string contentType)
        {
             await DeleteACartAsyncWithHttpInfo(cartId, accept, contentType);

        }

        /// <summary>
        /// Delete a Cart Deletes a *Cart*. Once a *Cart* has been deleted it can not be recovered.
        /// </summary>
        /// <exception cref="Carts.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cartId">This cart&#x27;s unique ID.</param>
        /// <param name="accept"></param>
        /// <param name="contentType"></param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> DeleteACartAsyncWithHttpInfo (string cartId, string accept, string contentType)
        {
            // verify the required parameter 'cartId' is set
            if (cartId == null)
                throw new ApiException(400, "Missing required parameter 'cartId' when calling CartApi->DeleteACart");
            // verify the required parameter 'accept' is set
            if (accept == null)
                throw new ApiException(400, "Missing required parameter 'accept' when calling CartApi->DeleteACart");
            // verify the required parameter 'contentType' is set
            if (contentType == null)
                throw new ApiException(400, "Missing required parameter 'contentType' when calling CartApi->DeleteACart");

            var localVarPath = "/carts/{cartId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (cartId != null) localVarPathParams.Add("cartId", this.Configuration.ApiClient.ParameterToString(cartId)); // path parameter
            if (accept != null) localVarHeaderParams.Add("Accept", this.Configuration.ApiClient.ParameterToString(accept)); // header parameter
            if (contentType != null) localVarHeaderParams.Add("Content-Type", this.Configuration.ApiClient.ParameterToString(contentType)); // header parameter
            // authentication (X-Auth-Token) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-Auth-Token")))
            {
                localVarHeaderParams["X-Auth-Token"] = this.Configuration.GetApiKeyWithPrefix("X-Auth-Token");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DeleteACart", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                null);
        }

        /// <summary>
        /// Get a Cart Returns a stores *Cart*.
        /// </summary>
        /// <exception cref="Carts.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cartId">The identifier of a specific cart.</param>
        /// <param name="accept"></param>
        /// <param name="contentType"></param>
        /// <param name="include">* &#x60;redirect_urls&#x60;: Create a direct link to a Cart. This can be used during the /POST request for Carts. * &#x60;line_items.physical_items.options&#x60;: The Cart returns an abbreviated result. Use this to return physical items product options. Can also be used in a /POST to have the extended Cart object return. * &#x60;line_items.digital_items.options&#x60;: The Cart returns an abbreviated result. Use this to return digital items product options.  Can also be used in a /POST to have the extended Cart object return. (optional)</param>
        /// <returns>CartFull1</returns>
        public CartFull1 GetACart (string cartId, string accept, string contentType, string include = null)
        {
             ApiResponse<CartFull1> localVarResponse = GetACartWithHttpInfo(cartId, accept, contentType, include);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get a Cart Returns a stores *Cart*.
        /// </summary>
        /// <exception cref="Carts.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cartId">The identifier of a specific cart.</param>
        /// <param name="accept"></param>
        /// <param name="contentType"></param>
        /// <param name="include">* &#x60;redirect_urls&#x60;: Create a direct link to a Cart. This can be used during the /POST request for Carts. * &#x60;line_items.physical_items.options&#x60;: The Cart returns an abbreviated result. Use this to return physical items product options. Can also be used in a /POST to have the extended Cart object return. * &#x60;line_items.digital_items.options&#x60;: The Cart returns an abbreviated result. Use this to return digital items product options.  Can also be used in a /POST to have the extended Cart object return. (optional)</param>
        /// <returns>ApiResponse of CartFull1</returns>
        public ApiResponse< CartFull1 > GetACartWithHttpInfo (string cartId, string accept, string contentType, string include = null)
        {
            // verify the required parameter 'cartId' is set
            if (cartId == null)
                throw new ApiException(400, "Missing required parameter 'cartId' when calling CartApi->GetACart");
            // verify the required parameter 'accept' is set
            if (accept == null)
                throw new ApiException(400, "Missing required parameter 'accept' when calling CartApi->GetACart");
            // verify the required parameter 'contentType' is set
            if (contentType == null)
                throw new ApiException(400, "Missing required parameter 'contentType' when calling CartApi->GetACart");

            var localVarPath = "/carts/{cartId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (cartId != null) localVarPathParams.Add("cartId", this.Configuration.ApiClient.ParameterToString(cartId)); // path parameter
            if (include != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "include", include)); // query parameter
            if (accept != null) localVarHeaderParams.Add("Accept", this.Configuration.ApiClient.ParameterToString(accept)); // header parameter
            if (contentType != null) localVarHeaderParams.Add("Content-Type", this.Configuration.ApiClient.ParameterToString(contentType)); // header parameter
            // authentication (X-Auth-Token) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-Auth-Token")))
            {
                localVarHeaderParams["X-Auth-Token"] = this.Configuration.GetApiKeyWithPrefix("X-Auth-Token");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetACart", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<CartFull1>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (CartFull1) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(CartFull1)));
        }

        /// <summary>
        /// Get a Cart Returns a stores *Cart*.
        /// </summary>
        /// <exception cref="Carts.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cartId">The identifier of a specific cart.</param>
        /// <param name="accept"></param>
        /// <param name="contentType"></param>
        /// <param name="include">* &#x60;redirect_urls&#x60;: Create a direct link to a Cart. This can be used during the /POST request for Carts. * &#x60;line_items.physical_items.options&#x60;: The Cart returns an abbreviated result. Use this to return physical items product options. Can also be used in a /POST to have the extended Cart object return. * &#x60;line_items.digital_items.options&#x60;: The Cart returns an abbreviated result. Use this to return digital items product options.  Can also be used in a /POST to have the extended Cart object return. (optional)</param>
        /// <returns>Task of CartFull1</returns>
        public async System.Threading.Tasks.Task<CartFull1> GetACartAsync (string cartId, string accept, string contentType, string include = null)
        {
             ApiResponse<CartFull1> localVarResponse = await GetACartAsyncWithHttpInfo(cartId, accept, contentType, include);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get a Cart Returns a stores *Cart*.
        /// </summary>
        /// <exception cref="Carts.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cartId">The identifier of a specific cart.</param>
        /// <param name="accept"></param>
        /// <param name="contentType"></param>
        /// <param name="include">* &#x60;redirect_urls&#x60;: Create a direct link to a Cart. This can be used during the /POST request for Carts. * &#x60;line_items.physical_items.options&#x60;: The Cart returns an abbreviated result. Use this to return physical items product options. Can also be used in a /POST to have the extended Cart object return. * &#x60;line_items.digital_items.options&#x60;: The Cart returns an abbreviated result. Use this to return digital items product options.  Can also be used in a /POST to have the extended Cart object return. (optional)</param>
        /// <returns>Task of ApiResponse (CartFull1)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<CartFull1>> GetACartAsyncWithHttpInfo (string cartId, string accept, string contentType, string include = null)
        {
            // verify the required parameter 'cartId' is set
            if (cartId == null)
                throw new ApiException(400, "Missing required parameter 'cartId' when calling CartApi->GetACart");
            // verify the required parameter 'accept' is set
            if (accept == null)
                throw new ApiException(400, "Missing required parameter 'accept' when calling CartApi->GetACart");
            // verify the required parameter 'contentType' is set
            if (contentType == null)
                throw new ApiException(400, "Missing required parameter 'contentType' when calling CartApi->GetACart");

            var localVarPath = "/carts/{cartId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (cartId != null) localVarPathParams.Add("cartId", this.Configuration.ApiClient.ParameterToString(cartId)); // path parameter
            if (include != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "include", include)); // query parameter
            if (accept != null) localVarHeaderParams.Add("Accept", this.Configuration.ApiClient.ParameterToString(accept)); // header parameter
            if (contentType != null) localVarHeaderParams.Add("Content-Type", this.Configuration.ApiClient.ParameterToString(contentType)); // header parameter
            // authentication (X-Auth-Token) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-Auth-Token")))
            {
                localVarHeaderParams["X-Auth-Token"] = this.Configuration.GetApiKeyWithPrefix("X-Auth-Token");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetACart", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<CartFull1>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (CartFull1) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(CartFull1)));
        }

        /// <summary>
        /// Update Customer ID Updates a *Carts* &#x60;customer_id&#x60;.  **Notes**  Changing the *Cart* &#x60;customer_id&#x60; will remove any promotions or shipping on the *Cart*. These are tied to the customer depending on cart conditions and any customer groups. 
        /// </summary>
        /// <exception cref="Carts.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="accept"></param>
        /// <param name="contentType"></param>
        /// <param name="cartId"></param>
        /// <param name="include">* &#x60;redirect_urls&#x60;: Create a direct link to a Cart. This can be used during the /POST request for Carts. * &#x60;line_items.physical_items.options&#x60;: The Cart returns an abbreviated result. Use this to return physical items product options. Can also be used in a /POST to have the extended Cart object return. * &#x60;line_items.digital_items.options&#x60;: The Cart returns an abbreviated result. Use this to return digital items product options.  Can also be used in a /POST to have the extended Cart object return. (optional)</param>
        /// <returns>CartFull1</returns>
        public CartFull1 UpdateACart (CartUpdatePutRequestData body, string accept, string contentType, string cartId, string include = null)
        {
             ApiResponse<CartFull1> localVarResponse = UpdateACartWithHttpInfo(body, accept, contentType, cartId, include);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Update Customer ID Updates a *Carts* &#x60;customer_id&#x60;.  **Notes**  Changing the *Cart* &#x60;customer_id&#x60; will remove any promotions or shipping on the *Cart*. These are tied to the customer depending on cart conditions and any customer groups. 
        /// </summary>
        /// <exception cref="Carts.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="accept"></param>
        /// <param name="contentType"></param>
        /// <param name="cartId"></param>
        /// <param name="include">* &#x60;redirect_urls&#x60;: Create a direct link to a Cart. This can be used during the /POST request for Carts. * &#x60;line_items.physical_items.options&#x60;: The Cart returns an abbreviated result. Use this to return physical items product options. Can also be used in a /POST to have the extended Cart object return. * &#x60;line_items.digital_items.options&#x60;: The Cart returns an abbreviated result. Use this to return digital items product options.  Can also be used in a /POST to have the extended Cart object return. (optional)</param>
        /// <returns>ApiResponse of CartFull1</returns>
        public ApiResponse< CartFull1 > UpdateACartWithHttpInfo (CartUpdatePutRequestData body, string accept, string contentType, string cartId, string include = null)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling CartApi->UpdateACart");
            // verify the required parameter 'accept' is set
            if (accept == null)
                throw new ApiException(400, "Missing required parameter 'accept' when calling CartApi->UpdateACart");
            // verify the required parameter 'contentType' is set
            if (contentType == null)
                throw new ApiException(400, "Missing required parameter 'contentType' when calling CartApi->UpdateACart");
            // verify the required parameter 'cartId' is set
            if (cartId == null)
                throw new ApiException(400, "Missing required parameter 'cartId' when calling CartApi->UpdateACart");

            var localVarPath = "/carts/{cartId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (cartId != null) localVarPathParams.Add("cartId", this.Configuration.ApiClient.ParameterToString(cartId)); // path parameter
            if (include != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "include", include)); // query parameter
            if (accept != null) localVarHeaderParams.Add("Accept", this.Configuration.ApiClient.ParameterToString(accept)); // header parameter
            if (contentType != null) localVarHeaderParams.Add("Content-Type", this.Configuration.ApiClient.ParameterToString(contentType)); // header parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }
            // authentication (X-Auth-Token) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-Auth-Token")))
            {
                localVarHeaderParams["X-Auth-Token"] = this.Configuration.GetApiKeyWithPrefix("X-Auth-Token");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("UpdateACart", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<CartFull1>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (CartFull1) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(CartFull1)));
        }

        /// <summary>
        /// Update Customer ID Updates a *Carts* &#x60;customer_id&#x60;.  **Notes**  Changing the *Cart* &#x60;customer_id&#x60; will remove any promotions or shipping on the *Cart*. These are tied to the customer depending on cart conditions and any customer groups. 
        /// </summary>
        /// <exception cref="Carts.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="accept"></param>
        /// <param name="contentType"></param>
        /// <param name="cartId"></param>
        /// <param name="include">* &#x60;redirect_urls&#x60;: Create a direct link to a Cart. This can be used during the /POST request for Carts. * &#x60;line_items.physical_items.options&#x60;: The Cart returns an abbreviated result. Use this to return physical items product options. Can also be used in a /POST to have the extended Cart object return. * &#x60;line_items.digital_items.options&#x60;: The Cart returns an abbreviated result. Use this to return digital items product options.  Can also be used in a /POST to have the extended Cart object return. (optional)</param>
        /// <returns>Task of CartFull1</returns>
        public async System.Threading.Tasks.Task<CartFull1> UpdateACartAsync (CartUpdatePutRequestData body, string accept, string contentType, string cartId, string include = null)
        {
             ApiResponse<CartFull1> localVarResponse = await UpdateACartAsyncWithHttpInfo(body, accept, contentType, cartId, include);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Update Customer ID Updates a *Carts* &#x60;customer_id&#x60;.  **Notes**  Changing the *Cart* &#x60;customer_id&#x60; will remove any promotions or shipping on the *Cart*. These are tied to the customer depending on cart conditions and any customer groups. 
        /// </summary>
        /// <exception cref="Carts.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="accept"></param>
        /// <param name="contentType"></param>
        /// <param name="cartId"></param>
        /// <param name="include">* &#x60;redirect_urls&#x60;: Create a direct link to a Cart. This can be used during the /POST request for Carts. * &#x60;line_items.physical_items.options&#x60;: The Cart returns an abbreviated result. Use this to return physical items product options. Can also be used in a /POST to have the extended Cart object return. * &#x60;line_items.digital_items.options&#x60;: The Cart returns an abbreviated result. Use this to return digital items product options.  Can also be used in a /POST to have the extended Cart object return. (optional)</param>
        /// <returns>Task of ApiResponse (CartFull1)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<CartFull1>> UpdateACartAsyncWithHttpInfo (CartUpdatePutRequestData body, string accept, string contentType, string cartId, string include = null)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling CartApi->UpdateACart");
            // verify the required parameter 'accept' is set
            if (accept == null)
                throw new ApiException(400, "Missing required parameter 'accept' when calling CartApi->UpdateACart");
            // verify the required parameter 'contentType' is set
            if (contentType == null)
                throw new ApiException(400, "Missing required parameter 'contentType' when calling CartApi->UpdateACart");
            // verify the required parameter 'cartId' is set
            if (cartId == null)
                throw new ApiException(400, "Missing required parameter 'cartId' when calling CartApi->UpdateACart");

            var localVarPath = "/carts/{cartId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (cartId != null) localVarPathParams.Add("cartId", this.Configuration.ApiClient.ParameterToString(cartId)); // path parameter
            if (include != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "include", include)); // query parameter
            if (accept != null) localVarHeaderParams.Add("Accept", this.Configuration.ApiClient.ParameterToString(accept)); // header parameter
            if (contentType != null) localVarHeaderParams.Add("Content-Type", this.Configuration.ApiClient.ParameterToString(contentType)); // header parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }
            // authentication (X-Auth-Token) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-Auth-Token")))
            {
                localVarHeaderParams["X-Auth-Token"] = this.Configuration.GetApiKeyWithPrefix("X-Auth-Token");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("UpdateACart", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<CartFull1>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (CartFull1) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(CartFull1)));
        }

    }
}
